#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# AI Management Installer + Sync
# Interactive install menu plus sync/deploy subcommand
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

# ── Common Setup ───────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
SKILLS_DIR="$SCRIPT_DIR/skills"
GROUPS_DIR="$SCRIPT_DIR/groups"
TEMPLATES_DIR="$SCRIPT_DIR/templates"
AI_MGMT_HOME="${AI_MANAGEMENT_HOME:-$HOME/ai-management}"
AI_MGMT_DIR="$AI_MGMT_HOME"
AGENTS_HOME="$AI_MGMT_HOME"
INSTALLED_DIR="$AI_MGMT_HOME/installed"
INSTALLED_FILE="$INSTALLED_DIR/skills.conf"
GITHUB_REPO="${AI_MANAGEMENT_REPO:-}"
GITHUB_BRANCH="${AI_MANAGEMENT_BRANCH:-main}"
MANAGED_DIRS=(agents skills hooks rules workflows mcp groups templates)
HARNESS_DIRS="claude codex copilot gemini __pycache__ backups"

REPO_ROOT=""
if [[ -d "$SCRIPT_DIR/agents" ]]; then
  REPO_ROOT="$SCRIPT_DIR"
fi

# ── Colors ────────────────────────────────────────────────────
BOLD='[1m'
RED='[0;31m'
GREEN='[0;32m'
YELLOW='[1;33m'
BLUE='[0;34m'
CYAN='[0;36m'
NC='[0m'

# ── Helpers ───────────────────────────────────────────────────
log()  { echo -e "${GREEN}✓${NC} $*"; }
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
info() { echo -e "${BLUE}→${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }

# ── Sync State ────────────────────────────────────────────────
sync_reset_state() {
  DRY_RUN=false
  REFRESH=false
  PURGE=false
  BACKUP=true
  PULL=false
  RESTORE=false
  RESTORE_LATEST=false
  RESTORE_FILE=""
  GLOBAL_MODE=false
  TARGETS=()
  SELECTED_GROUPS=()
  TEMPLATE=""

  TARGET_ROOT=""
  COPILOT_AGENTS_DIR=""
  CODEX_DIR=""
  CODEX_AGENTS_DIR=""
  CLAUDE_DIR=""
  GEMINI_DIR=""

  _GRP_AGENTS=()
  _GRP_SKILLS=()
  _GRP_RULES=()
  _GRP_WORKFLOWS=()
  _GRP_HOOKS=()
  _GRP_MCP=()

  RESOLVED_AGENTS=()
  RESOLVED_SKILLS=()
  RESOLVED_RULES=()
  RESOLVED_WORKFLOWS=()
  RESOLVED_HOOKS=()
  RESOLVED_MCP=()
}

sync_reset_state

# ── Load installed items for a content type ───────────────────
# Migrate legacy installed-skills.conf if present
_migrate_legacy() {
  local legacy="$AI_MGMT_HOME/installed-skills.conf"
  if [[ -f "$legacy" && ! -f "$INSTALLED_DIR/skills.conf" ]]; then
    mkdir -p "$INSTALLED_DIR"
    cp "$legacy" "$INSTALLED_DIR/skills.conf"
    rm -f "$legacy"
  fi
}
_migrate_legacy

load_installed() {
  load_installed_type "skills"
}

load_installed_type() {
  local type="$1"
  local conf="$INSTALLED_DIR/${type}.conf"
  INSTALLED_ITEMS=()
  if [[ -f "$conf" ]]; then
    while IFS= read -r line; do
      line="${line%%#*}"
      line="${line// /}"
      [[ -n "$line" ]] && INSTALLED_ITEMS+=("$line")
    done < "$conf"
  fi
  # Keep INSTALLED_SKILLS in sync for backward compat
  if [[ "$type" == "skills" ]]; then
    INSTALLED_SKILLS=("${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}")
  fi
}

is_installed() {
  local item="$1"
  for s in "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"; do
    [[ "$s" == "$item" ]] && return 0
  done
  return 1
}

save_installed() {
  save_installed_type "skills"
}

save_installed_type() {
  local type="$1"
  local conf="$INSTALLED_DIR/${type}.conf"
  mkdir -p "$INSTALLED_DIR"
  printf "# AI Management installed %s\n# Auto-generated by install.sh\n" "$type" > "$conf"
  for s in "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"; do
    echo "$s" >> "$conf"
  done
  # Keep INSTALLED_SKILLS in sync
  if [[ "$type" == "skills" ]]; then
    INSTALLED_SKILLS=("${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}")
  fi
}

# ── Discover available skills ─────────────────────────────────
get_all_skills() {
  get_all_type "skills"
}

# ── Discover all items for any content type ───────────────────
get_all_type() {
  local type="$1"
  local type_dir="$SCRIPT_DIR/$type"
  local -a items=()

  [[ -d "$type_dir" ]] || { return 0; }

  # Skills/hooks use subdirectories; agents/rules/workflows/mcp use .md files
  case "$type" in
    skills)
      for d in "$type_dir"/*/; do
        [[ -d "$d" ]] || continue
        local name
        name=$(basename "$d")
        # Skip build output dirs
        local skip=0
        for h in $HARNESS_DIRS; do [[ "$name" == "$h" ]] && skip=1; done
        [[ $skip -eq 1 ]] && continue
        [[ -f "$d/SKILL.md" ]] || continue
        items+=("$name")
      done
      ;;
    hooks)
      for entry in "$type_dir"/*; do
        [[ -e "$entry" ]] || continue
        local name
        name=$(basename "$entry")
        local skip=0
        for h in $HARNESS_DIRS; do [[ "$name" == "$h" ]] && skip=1; done
        [[ $skip -eq 1 ]] && continue
        items+=("$name")
      done
      ;;
    *)
      # agents, rules, workflows, mcp — flat .md files
      for f in "$type_dir"/*.md; do
        [[ -f "$f" ]] || continue
        local name
        name=$(basename "$f" .md)
        items+=("$name")
      done
      ;;
  esac

  printf '%s\n' "${items[@]+"${items[@]}"}" | sort
}

# ── Parse a group file for its [skills] section ───────────────
parse_group() {
  parse_group_section "$1" "skills"
}

# ── Parse any section from a group file ───────────────────────
parse_group_section() {
  local group_file="$1"
  local section="$2"
  local -a items=()
  local in_section=0

  while IFS= read -r line; do
    line="${line%%#*}"
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -z "$line" ]] && continue

    # Section header
    if [[ "$line" == "["*"]" ]]; then
      if [[ "$line" == "[$section]" ]]; then
        in_section=1
      else
        in_section=0
      fi
      continue
    fi

    if [[ $in_section -eq 1 ]]; then
      # Wildcard means all items in that type's directory
      if [[ "$line" == "*" ]]; then
        local type_dir="$SCRIPT_DIR/$section"
        if [[ -d "$type_dir" ]]; then
          for d in "$type_dir"/*/; do
            [[ -d "$d" ]] || continue
            local basename_d
            basename_d=$(basename "$d")
            [[ "$basename_d" == "__pycache__" ]] && continue
            items+=("$basename_d")
          done
        fi
      else
        items+=("$line")
      fi
    fi
  done < "$group_file"

  printf '%s\n' "${items[@]+"${items[@]}"}" | sort -u
}

# ── Get group description (first comment line) ────────────────
group_description() {
  head -1 "$1" | sed 's/^# //'
}

# ── Get skill description from SKILL.md frontmatter ───────────
skill_description() {
  local skill_dir="$SKILLS_DIR/$1"
  [[ -f "$skill_dir/SKILL.md" ]] || return
  # Extract description from YAML frontmatter
  sed -n '/^---$/,/^---$/p' "$skill_dir/SKILL.md" | grep -m1 "^description:" | sed "s/^description:[[:space:]]*//;s/^['\"]//;s/['\"]$//" | head -c 70
}

# ── Toggle selection in array ─────────────────────────────────
toggle_selection() {
  local item="$1"
  shift
  local -a arr=("$@")
  local found=false
  local -a new_arr=()

  for s in "${arr[@]+"${arr[@]}"}"; do
    if [[ "$s" == "$item" ]]; then
      found=true
    else
      new_arr+=("$s")
    fi
  done

  if ! $found; then
    new_arr+=("$item")
  fi

  printf '%s\n' "${new_arr[@]+"${new_arr[@]}"}"
}

is_in_array() {
  local item="$1"
  shift
  for s in "$@"; do
    [[ "$s" == "$item" ]] && return 0
  done
  return 1
}

# ═══════════════════════════════════════════════════════════════
# Interactive Menus
# ═══════════════════════════════════════════════════════════════

show_group_menu() {
  local -a selected_groups=()
  local -a groups=()
  local -a group_files=()

  for f in "$GROUPS_DIR"/*.group; do
    [[ -f "$f" ]] || continue
    local name
    name=$(basename "$f" .group)
    [[ "$name" == "all" ]] && continue
    # Only show groups that have a [skills] section
    grep -q '^\[skills\]' "$f" || continue
    groups+=("$name")
    group_files+=("$f")
  done

  while true; do
    clear
    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}║       Select Skill Groups                    ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo ""

    local i=1
    for idx in "${!groups[@]}"; do
      local name="${groups[$idx]}"
      local desc
      desc=$(group_description "${group_files[$idx]}")
      local skill_count
      skill_count=$(parse_group "${group_files[$idx]}" | wc -l | tr -d ' ')
      local marker="  "
      if is_in_array "$name" "${selected_groups[@]+"${selected_groups[@]}"}"; then
        marker="${GREEN}✓ ${NC}"
      fi
      printf "  ${marker}${BLUE}%2d)${NC} %-25s ${YELLOW}(%s skills)${NC}  %s\n" "$i" "$name" "$skill_count" "$desc"
      i=$((i + 1))
    done

    echo ""
    printf "  ${GREEN}✓ ${BLUE} a)${NC} Select ALL groups\n"
    printf "  ${RED}✗ ${BLUE} n)${NC} Deselect all\n"
    echo ""
    echo -e "  ${BOLD}Selected: ${#selected_groups[@]} groups${NC}"
    echo ""
    echo -e "  Enter number to toggle, ${GREEN}a${NC}ll, ${RED}n${NC}one, ${CYAN}i${NC}nstall, or ${RED}q${NC}uit:"
    read -rp "  > " choice

    case "$choice" in
      q|Q) return 1 ;;
      a|A)
        selected_groups=("${groups[@]}")
        ;;
      n|N)
        selected_groups=()
        ;;
      i|I)
        if [[ ${#selected_groups[@]} -eq 0 ]]; then
          warn "No groups selected"
          sleep 1
          continue
        fi
        # Resolve all skills from selected groups
        local -a resolved=()
        for grp in "${selected_groups[@]}"; do
          local grp_file="$GROUPS_DIR/${grp}.group"
          while IFS= read -r s; do
            [[ -n "$s" ]] && resolved+=("$s")
          done < <(parse_group "$grp_file")
        done
        # Deduplicate
        SKILLS_TO_INSTALL=($(printf '%s\n' "${resolved[@]}" | sort -u))
        return 0
        ;;
      *)
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#groups[@]} )); then
          local grp_name="${groups[$((choice - 1))]}"
          selected_groups=($(toggle_selection "$grp_name" "${selected_groups[@]+"${selected_groups[@]}"}"))
        fi
        ;;
    esac
  done
}

show_individual_menu() {
  local -a all_skills=()
  while IFS= read -r s; do
    [[ -n "$s" ]] && all_skills+=("$s")
  done < <(get_all_skills)

  local -a selected_skills=()
  local page=0
  local page_size=20
  local total=${#all_skills[@]}
  local total_pages=$(( (total + page_size - 1) / page_size ))

  while true; do
    clear
    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}║       Select Individual Skills               ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo -e "  Page $((page + 1))/$total_pages  |  Selected: ${#selected_skills[@]}/$total"
    echo ""

    local start=$((page * page_size))
    local end=$((start + page_size))
    (( end > total )) && end=$total

    local i=$((start + 1))
    for (( idx=start; idx<end; idx++ )); do
      local name="${all_skills[$idx]}"
      local marker="  "
      local installed_marker=""
      if is_in_array "$name" "${selected_skills[@]+"${selected_skills[@]}"}"; then
        marker="${GREEN}✓ ${NC}"
      fi
      if is_installed "$name"; then
        installed_marker=" ${CYAN}[installed]${NC}"
      fi
      local desc
      desc=$(skill_description "$name" 2>/dev/null || echo "")
      if [[ ${#desc} -gt 55 ]]; then
        desc="${desc:0:52}..."
      fi
      printf "  ${marker}${BLUE}%2d)${NC} %-35s %s${installed_marker}\n" "$i" "$name" "$desc"
      i=$((i + 1))
    done

    echo ""
    echo -e "  ${CYAN}<${NC} prev | ${CYAN}>${NC} next | ${GREEN}a${NC}ll | ${RED}n${NC}one | ${CYAN}i${NC}nstall | ${RED}q${NC}uit"
    read -rp "  > " choice

    case "$choice" in
      q|Q) return 1 ;;
      "<"|p|P)
        (( page > 0 )) && page=$((page - 1))
        ;;
      ">"|n_page|N_page)
        (( page < total_pages - 1 )) && page=$((page + 1))
        ;;
      a|A)
        selected_skills=("${all_skills[@]}")
        ;;
      n|N)
        selected_skills=()
        ;;
      i|I)
        if [[ ${#selected_skills[@]} -eq 0 ]]; then
          warn "No skills selected"
          sleep 1
          continue
        fi
        SKILLS_TO_INSTALL=("${selected_skills[@]}")
        return 0
        ;;
      *)
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= total )); then
          local skill_name="${all_skills[$((choice - 1))]}"
          selected_skills=($(toggle_selection "$skill_name" "${selected_skills[@]+"${selected_skills[@]}"}"))
        elif [[ "$choice" =~ ^[0-9]+-[0-9]+$ ]]; then
          # Range selection: e.g. 1-10
          local range_start="${choice%-*}"
          local range_end="${choice#*-}"
          for (( r=range_start; r<=range_end && r<=total; r++ )); do
            local skill_name="${all_skills[$((r - 1))]}"
            if ! is_in_array "$skill_name" "${selected_skills[@]+"${selected_skills[@]}"}"; then
              selected_skills+=("$skill_name")
            fi
          done
        fi
        ;;
    esac
  done
}

# ═══════════════════════════════════════════════════════════════
# Installation
# ═══════════════════════════════════════════════════════════════

install_skills() {
  install_type "skills" "$@"
}

# ── Generic installer for any content type ────────────────────
install_type() {
  local type="$1"
  shift
  local -a items=("$@")
  local type_dir="$SCRIPT_DIR/$type"

  echo ""
  echo -e "${BOLD}── Installing ${#items[@]} ${type} ──${NC}"

  load_installed_type "$type"

  local count=0
  for item in "${items[@]}"; do
    # Check existence: directories (skills/) or files (agents/)
    if [[ -d "$type_dir/$item" ]] || [[ -f "$type_dir/${item}.md" ]] || [[ -f "$type_dir/$item" ]]; then
      if ! is_installed "$item"; then
        INSTALLED_ITEMS+=("$item")
      fi
      ok "$item"
      count=$((count + 1))
    else
      warn "${type%s} not found: $item"
    fi
  done

  save_installed_type "$type"
  echo ""
  ok "Installed $count ${type} → $INSTALLED_DIR/${type}.conf"
  echo ""
  info "Run ${CYAN}$(basename "$0") sync${NC} to deploy to your harnesses"
}

# ═══════════════════════════════════════════════════════════════
# Uninstall
# ═══════════════════════════════════════════════════════════════

uninstall_menu() {
  load_installed

  if [[ ${#INSTALLED_SKILLS[@]} -eq 0 ]]; then
    warn "No skills installed"
    return
  fi

  echo ""
  echo -e "${BOLD}── Installed Skills ──${NC}"
  local i=1
  for s in "${INSTALLED_SKILLS[@]}"; do
    printf "  ${BLUE}%2d)${NC} %s\n" "$i" "$s"
    i=$((i + 1))
  done
  echo ""
  echo -e "  Enter numbers to uninstall (comma-separated), ${RED}a${NC}ll, or ${RED}q${NC}uit:"
  read -rp "  > " choice

  case "$choice" in
    q|Q) return ;;
    a|A)
      INSTALLED_SKILLS=()
      save_installed
      ok "Uninstalled all skills"
      ;;
    *)
      local -a new_installed=("${INSTALLED_SKILLS[@]}")
      IFS=',' read -ra nums <<< "$choice"
      for num in "${nums[@]}"; do
        num="$(echo "$num" | tr -d ' ')"
        if [[ "$num" =~ ^[0-9]+$ ]] && (( num >= 1 && num <= ${#INSTALLED_SKILLS[@]} )); then
          local skill="${INSTALLED_SKILLS[$((num - 1))]}"
          new_installed=($(toggle_selection "$skill" "${new_installed[@]}"))
          ok "Uninstalled: $skill"
        fi
      done
      INSTALLED_SKILLS=("${new_installed[@]+"${new_installed[@]}"}")
      save_installed
      ;;
  esac
}

# ═══════════════════════════════════════════════════════════════
# Main Menu
# ═══════════════════════════════════════════════════════════════

main_menu() {
  while true; do
    clear
    load_installed
    local installed_count=${#INSTALLED_SKILLS[@]}
    local total_count
    total_count=$(get_all_skills | wc -l | tr -d ' ')

    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${CYAN}$total_count${NC} skills available  |  ${GREEN}$installed_count${NC} installed"
    echo ""
    echo -e "  ${BLUE}1)${NC} Browse by ${BOLD}group${NC}        (categories of related skills)"
    echo -e "  ${BLUE}2)${NC} Browse ${BOLD}individual${NC}      (pick specific skills)"
    echo -e "  ${BLUE}3)${NC} Install ${GREEN}all${NC} skills"
    echo -e "  ${BLUE}4)${NC} ${RED}Uninstall${NC} skills"
    echo -e "  ${BLUE}5)${NC} Show installed"
    echo -e "  ${BLUE}q)${NC} Quit"
    echo ""
    read -rp "  > " choice

    case "$choice" in
      1)
        SKILLS_TO_INSTALL=()
        if show_group_menu; then
          install_skills "${SKILLS_TO_INSTALL[@]}"
          read -rp "  Press Enter to continue..."
        fi
        ;;
      2)
        SKILLS_TO_INSTALL=()
        if show_individual_menu; then
          install_skills "${SKILLS_TO_INSTALL[@]}"
          read -rp "  Press Enter to continue..."
        fi
        ;;
      3)
        local -a all=()
        while IFS= read -r s; do
          [[ -n "$s" ]] && all+=("$s")
        done < <(get_all_skills)
        install_skills "${all[@]}"
        read -rp "  Press Enter to continue..."
        ;;
      4)
        uninstall_menu
        read -rp "  Press Enter to continue..."
        ;;
      5)
        echo ""
        echo -e "${BOLD}── Installed Skills ──${NC}"
        if [[ $installed_count -eq 0 ]]; then
          info "No skills installed"
        else
          for s in "${INSTALLED_SKILLS[@]}"; do
            echo -e "  ${GREEN}✓${NC} $s"
          done
        fi
        echo ""
        read -rp "  Press Enter to continue..."
        ;;
      q|Q) break ;;
    esac
  done
}
# ── Pull: download latest from GitHub ────────────────────────
# Downloads the repo tarball, extracts managed directories into
# ~/ai-management as real files (no local clone needed).
pull_from_github() {
  if [[ -z "$GITHUB_REPO" ]]; then
    err "No repository configured for --pull."
    echo ""
    echo "  Set the AI_MANAGEMENT_REPO environment variable to your GitHub repo:"
    echo "    export AI_MANAGEMENT_REPO=\"your-org/your-ai-management-repo\""
    echo ""
    echo "  Or set it in your shell profile (~/.zshrc, ~/.bashrc)."
    exit 1
  fi

  local api_path="repos/${GITHUB_REPO}/tarball/${GITHUB_BRANCH}"
  local curl_url="https://github.com/${GITHUB_REPO}/archive/refs/heads/${GITHUB_BRANCH}.tar.gz"

  echo ""
  echo -e "${BOLD}── Pulling from GitHub (${GITHUB_REPO}@${GITHUB_BRANCH}) ──${NC}"

  local scratch_dir="$AI_MGMT_DIR/.pull-work-$$-$RANDOM"
  rm -rf "$scratch_dir"
  mkdir -p "$scratch_dir"

  info "Downloading tarball…"
  local ok=false

  # Try gh CLI first (handles private repos with existing auth)
  if command -v gh &>/dev/null; then
    if gh api "$api_path" 2>/dev/null | tar xz -C "$scratch_dir" 2>/dev/null; then
      ok=true
    fi
  fi

  # Fall back to curl (public repos, no auth required)
  if ! $ok && command -v curl &>/dev/null; then
    if curl -sfL "$curl_url" | tar xz -C "$scratch_dir" 2>/dev/null; then
      ok=true
    fi
  fi

  if ! $ok; then
    err "Failed to download from ${GITHUB_REPO}. Ensure 'gh' is authenticated or the repo is public."
    rm -rf "$scratch_dir"
    exit 1
  fi

  # The tarball extracts into a single directory
  local extracted
  extracted=$(ls -1d "$scratch_dir"/*/ 2>/dev/null | head -1)
  if [[ -z "$extracted" ]]; then
    err "Tarball extraction failed — no directory found"
    rm -rf "$scratch_dir"
    exit 1
  fi

  mkdir -p "$AI_MGMT_DIR"

  for dir in "${MANAGED_DIRS[@]}"; do
    local src="$extracted$dir"
    local dest="$AI_MGMT_DIR/$dir"
    [[ -d "$src" ]] || continue

    # Remove existing symlink — we're replacing with real files
    [[ -L "$dest" ]] && rm -f "$dest"

    # Remove existing real dir and replace with fresh copy
    [[ -d "$dest" ]] && rm -rf "$dest"

    cp -R "$src" "$dest"
    local count
    count=$(find "$dest" -type f 2>/dev/null | wc -l | tr -d ' ')
    log "Pulled $dir/ ($count files)"
  done

  # Also pull defaults.conf and install.sh if present
  [[ -f "$extracted/defaults.conf" ]] && cp "$extracted/defaults.conf" "$AI_MGMT_DIR/defaults.conf"
  [[ -f "$extracted/install.sh" ]] && cp "$extracted/install.sh" "$AI_MGMT_DIR/install.sh" && chmod +x "$AI_MGMT_DIR/install.sh"

  rm -rf "$scratch_dir"

  echo ""
  log "Pull complete → $AI_MGMT_DIR"
}

# ── Setup: ensure ~/ai-management is populated ──────────────
# If a local repo checkout exists, symlinks its subdirs into
# ~/ai-management. Otherwise, checks that ~/ai-management already
# has content (from a previous --pull). If neither, advises
# the user to run --pull.
setup_ai_mgmt_dir() {
  mkdir -p "$AI_MGMT_DIR"

  # If we have a local repo checkout, symlink its dirs
  if [[ -n "$REPO_ROOT" ]]; then
    # Guard: skip if REPO_ROOT resolved to ~/ai-management itself (self-reference)
    local real_mgmt real_repo
    real_mgmt="$(cd "$AI_MGMT_DIR" && pwd -P)"
    real_repo="$(cd "$REPO_ROOT" && pwd -P)"
    if [[ "$real_repo" == "$real_mgmt" ]]; then
      return
    fi

    for dir in "${MANAGED_DIRS[@]}"; do
      local src="$REPO_ROOT/$dir"
      local dest="$AI_MGMT_DIR/$dir"
      [[ -d "$src" ]] || continue
      if [[ -L "$dest" ]]; then
        local current
        current=$(readlink "$dest" 2>/dev/null || true)
        [[ "$current" == "$src" ]] && continue
        rm -f "$dest"
      elif [[ -d "$dest" ]]; then
        # Real directory exists (e.g. from --pull) — skip
        continue
      fi
      ln -s "$src" "$dest"
      info "Linked $dir/ → $dest"
    done
  fi
}
# Helper: check if array contains a value (Bash 3.2 compatible)
array_contains() {
  local needle="$1"; shift
  local item
  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done
  return 1
}

# Helper: expand a wildcard or name list for a given section
resolve_section() {
  local section="$1" dir="$2"
  shift 2
  local -a names=("$@")

  # Wildcard — return all matching files in the directory
  if array_contains "*" "${names[@]}"; then
    case "$section" in
      agents|rules|workflows)
        for f in "$dir"/*.md; do
          [[ -f "$f" ]] || continue
          echo "$f"
        done
        ;;
      skills)
        for d in "$dir"/*/; do
          [[ -d "$d" ]] || continue
          [[ -f "$d/SKILL.md" || -f "$d/skill.md" ]] || continue
          echo "$d"
        done
        ;;
      mcp)
        for f in "$dir"/*.json "$dir"/*.yaml "$dir"/*.yml "$dir"/*.md; do
          [[ -f "$f" ]] || continue
          echo "$f"
        done
        ;;
    esac
    return
  fi

  # Explicit names — resolve each
  local name
  for name in "${names[@]}"; do
    case "$section" in
      agents|rules|workflows)
        local path="$dir/${name}.md"
        if [[ -f "$path" ]]; then
          echo "$path"
        else
          warn "Group entry not found: $section/$name (.md)"
        fi
        ;;
      skills)
        local path="$dir/${name}"
        if [[ -d "$path" ]]; then
          echo "$path/"
        else
          warn "Group entry not found: $section/$name (directory)"
        fi
        ;;
      mcp)
        local found=false
        for ext in md json yaml yml; do
          local path="$dir/${name}.${ext}"
          if [[ -f "$path" ]]; then
            echo "$path"
            found=true
            break
          fi
        done
        $found || warn "Group entry not found: $section/$name (.md/.json/.yaml/.yml)"
        ;;
    esac
  done
}

# Parse a .group file into section arrays
parse_group_file() {
  local group_file="$1"
  local current_section=""

  while IFS= read -r line; do
    # Strip leading/trailing whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    # Skip blank lines and comments
    [[ -z "$line" || "$line" == \#* ]] && continue
    # Section header
    if [[ "$line" =~ ^\[([a-z]+)\]$ ]]; then
      current_section="${BASH_REMATCH[1]}"
      continue
    fi
    # Entry under a section
    if [[ -n "$current_section" ]]; then
      case "$current_section" in
        agents)    _GRP_AGENTS+=("$line") ;;
        skills)    _GRP_SKILLS+=("$line") ;;
        rules)     _GRP_RULES+=("$line") ;;
        workflows) _GRP_WORKFLOWS+=("$line") ;;
        hooks)     _GRP_HOOKS+=("$line") ;;
        mcp)       _GRP_MCP+=("$line") ;;
        *)         warn "Unknown group section: [$current_section]" ;;
      esac
    fi
  done < "$group_file"
}
# ── Helper: back up agent files before changes ───────────────
backup_path() {
  local label="$1" path="$2"

  local -a files_to_backup=()
  local backup_dir

  if [[ -d "$path" ]]; then
    backup_dir="$path/backups"
    while IFS= read -r -d '' f; do
      files_to_backup+=("$f")
    done < <(find "$path" -maxdepth 1 \( -type f -o -type l \) -print0 2>/dev/null)
  elif [[ -e "$path" ]]; then
    backup_dir="$(dirname "$path")/backups"
    files_to_backup+=("$path")
  fi

  if [[ ${#files_to_backup[@]} -eq 0 ]]; then
    return
  fi

  # Filter to files/file-symlinks only (skip directory symlinks)
  local -a valid_files=()
  for f in "${files_to_backup[@]}"; do
    [[ -f "$f" ]] && valid_files+=("$f")
  done
  if [[ ${#valid_files[@]} -eq 0 ]]; then
    return
  fi

  local type_name
  if [[ -d "$path" ]]; then
    type_name=$(basename "$path")
  else
    type_name=$(basename "$path" | sed 's/\.[^.]*$//')
  fi

  local timestamp
  timestamp=$(date '+%Y%m%d-%H%M%S')
  local zip_file="$backup_dir/${label}-${type_name}-${timestamp}.zip"

  if $DRY_RUN; then
    info "[dry-run] Would back up ${#valid_files[@]} ${type_name} files → $(basename "$zip_file")"
    return
  fi

  mkdir -p "$backup_dir"
  if zip -jq "$zip_file" "${valid_files[@]}" 2>/dev/null; then
    log "$label: backed up ${#valid_files[@]} ${type_name} files → $(basename "$zip_file")"
  fi
}

# ── Helper: resolve all managed paths for a target ───────────
managed_paths_for() {
  case "$1" in
    copilot)
      echo "$COPILOT_AGENTS_DIR"
      echo "$TARGET_ROOT/.copilot/skills"
      echo "$TARGET_ROOT/.copilot/instructions"
      echo "$TARGET_ROOT/.copilot/workflows"
      echo "$TARGET_ROOT/.copilot/hooks"
      [[ -f "$TARGET_ROOT/.copilot/mcp.json" ]] && echo "$TARGET_ROOT/.copilot/mcp.json"
      ;;
    codex)
      echo "$CODEX_AGENTS_DIR"
      echo "$CODEX_DIR/skills"
      echo "$CODEX_DIR/instructions"
      echo "$CODEX_DIR/workflows"
      echo "$CODEX_DIR/hooks"
      [[ -f "$CODEX_DIR/mcp-servers.json" ]] && echo "$CODEX_DIR/mcp-servers.json"
      ;;
    claude)
      echo "$CLAUDE_DIR/agents"
      echo "$CLAUDE_DIR/skills"
      echo "$CLAUDE_DIR/rules"
      echo "$CLAUDE_DIR/workflows"
      echo "$CLAUDE_DIR/hooks"
      [[ -f "$CLAUDE_DIR/mcp.json" ]] && echo "$CLAUDE_DIR/mcp.json"
      ;;
    gemini)
      [[ -f "$GEMINI_DIR/GEMINI.md" ]] && echo "$GEMINI_DIR/GEMINI.md"
      [[ -f "$GEMINI_DIR/mcp-servers.json" ]] && echo "$GEMINI_DIR/mcp-servers.json"
      ;;
  esac
}

# ── Helper: resolve restore directory for a target ───────────
restore_paths_for() {
  local paths=()
  while IFS= read -r p; do
    [[ -n "$p" ]] && paths+=("$p")
  done < <(managed_paths_for "$1")

  for path in "${paths[@]}"; do
    if [[ -d "$path" || ! -e "$path" ]]; then
      local real_path="$path"
      real_path="${real_path%/}"
      echo "${real_path}/backups|${real_path}"
    else
      local parent
      parent=$(dirname "$path")
      echo "${parent}/backups|${parent}"
    fi
  done
}

all_backup_dirs_for() {
  case "$1" in
    copilot)
      echo "$COPILOT_AGENTS_DIR/backups|$COPILOT_AGENTS_DIR"
      echo "$TARGET_ROOT/.copilot/skills/backups|$TARGET_ROOT/.copilot/skills"
      echo "$TARGET_ROOT/.copilot/instructions/backups|$TARGET_ROOT/.copilot/instructions"
      echo "$TARGET_ROOT/.copilot/workflows/backups|$TARGET_ROOT/.copilot/workflows"
      echo "$TARGET_ROOT/.copilot/hooks/backups|$TARGET_ROOT/.copilot/hooks"
      echo "$TARGET_ROOT/.copilot/backups|$TARGET_ROOT/.copilot"
      ;;
    codex)
      echo "$CODEX_AGENTS_DIR/backups|$CODEX_AGENTS_DIR"
      echo "$CODEX_DIR/skills/backups|$CODEX_DIR/skills"
      echo "$CODEX_DIR/instructions/backups|$CODEX_DIR/instructions"
      echo "$CODEX_DIR/workflows/backups|$CODEX_DIR/workflows"
      echo "$CODEX_DIR/hooks/backups|$CODEX_DIR/hooks"
      echo "$CODEX_DIR/backups|$CODEX_DIR"
      ;;
    claude)
      echo "$CLAUDE_DIR/agents/backups|$CLAUDE_DIR/agents"
      echo "$CLAUDE_DIR/skills/backups|$CLAUDE_DIR/skills"
      echo "$CLAUDE_DIR/rules/backups|$CLAUDE_DIR/rules"
      echo "$CLAUDE_DIR/workflows/backups|$CLAUDE_DIR/workflows"
      echo "$CLAUDE_DIR/hooks/backups|$CLAUDE_DIR/hooks"
      echo "$CLAUDE_DIR/backups|$CLAUDE_DIR"
      ;;
    gemini)
      echo "$GEMINI_DIR/backups|$GEMINI_DIR"
      ;;
  esac
}

# ── Helper: restore from a zip backup ────────────────────────
do_restore() {
  local label="$1" backup_dir="$2" restore_dir="$3" zip_file="$4"

  if [[ ! -f "$zip_file" ]]; then
    err "$label: backup not found — $zip_file"
    return 1
  fi

  local file_count
  file_count=$(zipinfo -1 "$zip_file" 2>/dev/null | wc -l | tr -d ' ')

  if $DRY_RUN; then
    info "[dry-run] Would restore $file_count files from $(basename "$zip_file") → $restore_dir"
    return
  fi

  mkdir -p "$restore_dir"
  unzip -joq "$zip_file" -d "$restore_dir" 2>/dev/null
  log "$label: restored $file_count files from $(basename "$zip_file") → $restore_dir/"
}

# ── Helper: run restore for a single target ──────────────────
restore_target() {
  local target="$1"
  local label="$target"

  echo ""
  echo -e "${BOLD}── Restoring $label files ──${NC}"

  if [[ -n "$RESTORE_FILE" ]]; then
    local found=false
    while IFS='|' read -r bdir rdir; do
      local zip_path="$bdir/$RESTORE_FILE"
      [[ -f "$RESTORE_FILE" ]] && zip_path="$RESTORE_FILE"
      if [[ -f "$zip_path" ]]; then
        do_restore "$label" "$bdir" "$rdir" "$zip_path"
        found=true
        break
      fi
    done < <(all_backup_dirs_for "$target")
    if ! $found; then
      err "$label: backup file not found — $RESTORE_FILE"
    fi

  elif $RESTORE_LATEST; then
    local any_found=false
    while IFS='|' read -r bdir rdir; do
      [[ -d "$bdir" ]] || continue
      local latest
      latest=$(ls -1t "$bdir"/*.zip 2>/dev/null | head -1)
      if [[ -n "$latest" ]]; then
        do_restore "$label ($(basename "$rdir"))" "$bdir" "$rdir" "$latest"
        any_found=true
      fi
    done < <(all_backup_dirs_for "$target")
    if ! $any_found; then
      warn "$label: no backups found"
    fi

  else
    local -a all_zips=() all_rdirs=() all_bdirs=()
    while IFS='|' read -r bdir rdir; do
      [[ -d "$bdir" ]] || continue
      while IFS= read -r f; do
        [[ -n "$f" ]] && all_zips+=("$f") && all_rdirs+=("$rdir") && all_bdirs+=("$bdir")
      done < <(ls -1t "$bdir"/*.zip 2>/dev/null)
    done < <(all_backup_dirs_for "$target")

    if [[ ${#all_zips[@]} -eq 0 ]]; then
      warn "$label: no backups found"
      return
    fi

    echo ""
    echo -e "  ${BOLD}Available backups for $label:${NC}"
    local i=1
    for b in "${all_zips[@]}"; do
      local name size type_hint
      name=$(basename "$b")
      size=$(du -h "$b" | cut -f1 | tr -d ' ')
      type_hint=$(basename "${all_rdirs[$((i-1))]}")
      printf "    ${BLUE}%d)${NC} %-50s ${YELLOW}(%s)${NC}  [%s]\n" "$i" "$name" "$size" "$type_hint"
      i=$((i + 1))
    done
    echo ""
    read -rp "  Enter number to restore (or 'q' to skip): " choice

    if [[ "$choice" == "q" || -z "$choice" ]]; then
      info "$label: skipped"
      return
    fi

    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#all_zips[@]} )); then
      local idx=$((choice - 1))
      do_restore "$label" "${all_bdirs[$idx]}" "${all_rdirs[$idx]}" "${all_zips[$idx]}"
    else
      err "Invalid selection"
    fi
  fi
}

# ── Helper: make symlink ─────────────────────────────────────
make_link() {
  local src="$1" dest="$2"
  if $DRY_RUN; then
    info "[dry-run] symlink: $src → $dest"
    return
  fi
  [[ -e "$dest" || -L "$dest" ]] && rm -f "$dest"
  ln -s "$src" "$dest"
}

# ── Helper: safely remove symlinks from a dir ────────────────
purge_symlinks_in() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -maxdepth 1 -type l -not -name backups -not -path "*/backups/*" -delete 2>/dev/null || true
}

# ── Helper: sync skills to a target directory ────────────────
sync_skills_to() {
  local target_dir="$1" harness="$2" label="$3"
  [[ ${#RESOLVED_SKILLS[@]} -eq 0 ]] && return 0

  if $REFRESH; then
    info "Cleaning existing skill symlinks in $target_dir"
    purge_symlinks_in "$target_dir"
  fi

  local build_dir="$AGENTS_HOME/skills/$harness"
  local skills_count=0
  for skill_dir in "${RESOLVED_SKILLS[@]}"; do
    [[ -d "$skill_dir" ]] || continue
    local skill_name
    skill_name=$(basename "$skill_dir")
    local built_skill="$build_dir/$skill_name"
    [[ -d "$built_skill" ]] || continue
    mkdir -p "$target_dir"
    make_link "$built_skill" "$target_dir/$skill_name"
    skills_count=$((skills_count + 1))
  done
  if [[ $skills_count -gt 0 ]]; then
    log "$label: symlinked $skills_count skills → $target_dir/"
  fi

  return 0
}

# ── Helper: sync rules to a target directory ─────────────────
sync_rules_to() {
  local target_dir="$1" harness="$2" label="$3"
  [[ ${#RESOLVED_RULES[@]} -eq 0 ]] && return 0

  if $REFRESH; then
    purge_symlinks_in "$target_dir"
  fi

  local build_dir="$AGENTS_HOME/rules/$harness"
  local count=0
  for rule_file in "${RESOLVED_RULES[@]}"; do
    [[ -f "$rule_file" ]] || continue
    local rule_name
    rule_name=$(basename "$rule_file")
    local built_rule="$build_dir/$rule_name"
    [[ -f "$built_rule" ]] || continue
    mkdir -p "$target_dir"
    make_link "$built_rule" "$target_dir/$rule_name"
    count=$((count + 1))
  done
  if [[ $count -gt 0 ]]; then
    log "$label: symlinked $count rules → $target_dir/"
  fi

  return 0
}

# ── Helper: sync workflows to a target directory ─────────────
sync_workflows_to() {
  local target_dir="$1" harness="$2" label="$3"
  [[ ${#RESOLVED_WORKFLOWS[@]} -eq 0 ]] && return 0

  if $REFRESH; then
    purge_symlinks_in "$target_dir"
  fi

  local build_dir="$AGENTS_HOME/workflows/$harness"
  local count=0
  for wf_file in "${RESOLVED_WORKFLOWS[@]}"; do
    [[ -f "$wf_file" ]] || continue
    local wf_name
    wf_name=$(basename "$wf_file")
    local built_wf="$build_dir/$wf_name"
    [[ -f "$built_wf" ]] || continue
    mkdir -p "$target_dir"
    make_link "$built_wf" "$target_dir/$wf_name"
    count=$((count + 1))
  done
  if [[ $count -gt 0 ]]; then
    log "$label: symlinked $count workflows → $target_dir/"
  fi

  return 0
}

# ── Helper: sync hooks to a target directory ─────────────────
sync_hooks_to() {
  local target_dir="$1" harness="$2" label="$3"
  local build_dir="$AGENTS_HOME/hooks/$harness"
  [[ -d "$build_dir" ]] || return 0

  local hook_files=()
  while IFS= read -r -d '' f; do
    hook_files+=("$f")
  done < <(find "$build_dir" -maxdepth 1 -type f -print0 2>/dev/null)
  [[ ${#hook_files[@]} -eq 0 ]] && return 0

  if $REFRESH; then
    purge_symlinks_in "$target_dir"
  fi

  local count=0
  for hook_file in "${hook_files[@]}"; do
    local hook_name
    hook_name=$(basename "$hook_file")
    mkdir -p "$target_dir"
    make_link "$hook_file" "$target_dir/$hook_name"
    count=$((count + 1))
  done
  if [[ $count -gt 0 ]]; then
    log "$label: symlinked $count hooks → $target_dir/"
  fi

  return 0
}

# ── Helper: sync MCP config to a harness ─────────────────────
sync_mcp_to() {
  local harness="$1" label="$2"
  [[ ${#RESOLVED_MCP[@]} -eq 0 ]] && return 0

  local build_dir="$AGENTS_HOME/mcp/$harness"
  [[ -d "$build_dir" ]] || return 0

  local mcp_entries=()
  for mcp_file in "${RESOLVED_MCP[@]}"; do
    [[ -e "$mcp_file" ]] || continue
    local mcp_name
    mcp_name=$(basename "$mcp_file")
    mcp_name="${mcp_name%.*}"
    local built_mcp="$build_dir/${mcp_name}.json"
    [[ -f "$built_mcp" ]] || continue
    mcp_entries+=("$built_mcp")
  done
  [[ ${#mcp_entries[@]} -eq 0 ]] && return 0

  local combined
  case "$harness" in
    copilot)
      combined="$TARGET_ROOT/.copilot/mcp.json"
      ;;
    claude)
      combined="$CLAUDE_DIR/mcp.json"
      ;;
    codex)
      combined="$CODEX_DIR/mcp-servers.json"
      ;;
    gemini)
      combined="$GEMINI_DIR/mcp-servers.json"
      ;;
    *)
      return ;;
  esac

  if $DRY_RUN; then
    info "[dry-run] Would write ${#mcp_entries[@]} MCP servers to $combined"
    return
  fi

  local json_content
  json_content=$(python3 -c "
import json, sys, os
servers = {}
for path in sys.argv[1:]:
    with open(path) as f:
        data = json.load(f)
    name = os.path.splitext(os.path.basename(path))[0]
    servers[name] = data
print(json.dumps({'mcpServers': servers}, indent=2))
" "${mcp_entries[@]}")

  mkdir -p "$(dirname "$combined")"
  echo "$json_content" > "$combined"
  log "$label: wrote ${#mcp_entries[@]} MCP servers → $combined"
}

# ── Helper: build harness-specific files for all content types ──
build_all() {
  local harnesses="$1"
  local build_script="$SCRIPT_DIR/skills/AI-Management/build.py"

  if [[ ! -f "$build_script" ]]; then
    build_script="$AGENTS_HOME/skills/AI-Management/build.py"
  fi

  if [[ ! -f "$build_script" ]]; then
    err "Build script not found: $build_script"
    exit 1
  fi

  if ! command -v python3 &>/dev/null; then
    err "python3 is required for the build step but was not found"
    exit 1
  fi

  local types=("agents" "skills" "rules" "workflows" "mcp" "hooks")

  for content_type in "${types[@]}"; do
    local source_dir="$AGENTS_HOME/$content_type"
    [[ -d "$source_dir" ]] || continue

    local has_sources=false
    case "$content_type" in
      agents|rules|workflows)
        [[ -n "$(find -L "$source_dir" -maxdepth 1 -name '*.md' 2>/dev/null | head -1)" ]] && has_sources=true ;;
      skills)
        for d in "$source_dir"/*/; do
          [[ -d "$d" ]] && local dname=$(basename "$d") && \
            [[ "$dname" != "copilot" && "$dname" != "claude" && "$dname" != "codex" && "$dname" != "gemini" ]] && \
            has_sources=true && break
        done ;;
      mcp)
        [[ -n "$(find -L "$source_dir" -maxdepth 1 \( -name '*.json' -o -name '*.md' \) 2>/dev/null | head -1)" ]] && has_sources=true ;;
      hooks)
        [[ -n "$(find -L "$source_dir" -maxdepth 1 -type f 2>/dev/null | grep -v '^\.' | head -1)" ]] && has_sources=true ;;
    esac
    $has_sources || continue

    if $DRY_RUN; then
      info "[dry-run] Would build harness-specific $content_type for: $harnesses"
      python3 "$build_script" "$source_dir" --type "$content_type" --harness "$harnesses" --dry-run
    else
      python3 "$build_script" "$source_dir" --type "$content_type" --harness "$harnesses" --quiet
    fi
  done
}

# ═════════════════════════════════════════════════════════════
# COPILOT — symlink individual agent .md files
# ═════════════════════════════════════════════════════════════
sync_copilot() {
  echo ""
  echo -e "${BOLD}── Syncing to GitHub Copilot CLI ──${NC}"

  mkdir -p "$COPILOT_AGENTS_DIR"

  if $REFRESH; then
    info "Cleaning existing symlinks in $COPILOT_AGENTS_DIR"
    purge_symlinks_in "$COPILOT_AGENTS_DIR"
  fi

  local build_dir="$AGENTS_HOME/agents/copilot"
  local count=0
  for agent_file in "${RESOLVED_AGENTS[@]}"; do
    [[ -f "$agent_file" ]] || continue
    local basename
    basename=$(basename "$agent_file")
    local built_file="$build_dir/$basename"
    [[ -f "$built_file" ]] || continue
    make_link "$built_file" "$COPILOT_AGENTS_DIR/$basename"
    count=$((count + 1))
  done
  log "Copilot: symlinked $count agent files → $COPILOT_AGENTS_DIR/"

  sync_skills_to "$TARGET_ROOT/.copilot/skills" "copilot" "Copilot"
  sync_rules_to "$TARGET_ROOT/.copilot/instructions" "copilot" "Copilot"
  sync_workflows_to "$TARGET_ROOT/.copilot/workflows" "copilot" "Copilot"
  sync_hooks_to "$TARGET_ROOT/.copilot/hooks" "copilot" "Copilot"
  sync_mcp_to "copilot" "Copilot"
}

# ═════════════════════════════════════════════════════════════
# CODEX — symlink individual agent .md files
# ═════════════════════════════════════════════════════════════
sync_codex() {
  echo ""
  echo -e "${BOLD}── Syncing to OpenAI Codex CLI ──${NC}"

  mkdir -p "$CODEX_AGENTS_DIR"

  if $REFRESH; then
    info "Cleaning existing symlinks in $CODEX_AGENTS_DIR"
    purge_symlinks_in "$CODEX_AGENTS_DIR"
  fi

  local build_dir="$AGENTS_HOME/agents/codex"
  local count=0
  for agent_file in "${RESOLVED_AGENTS[@]}"; do
    [[ -f "$agent_file" ]] || continue
    local basename
    basename=$(basename "$agent_file")
    local built_file="$build_dir/$basename"
    [[ -f "$built_file" ]] || continue
    make_link "$built_file" "$CODEX_AGENTS_DIR/$basename"
    count=$((count + 1))
  done
  log "Codex: symlinked $count agent files → $CODEX_AGENTS_DIR/"

  sync_skills_to "$CODEX_DIR/skills" "codex" "Codex"
  sync_rules_to "$CODEX_DIR/instructions" "codex" "Codex"
  sync_workflows_to "$CODEX_DIR/workflows" "codex" "Codex"
  sync_hooks_to "$CODEX_DIR/hooks" "codex" "Codex"
  sync_mcp_to "codex" "Codex"
}

# ═════════════════════════════════════════════════════════════
# CLAUDE CODE — symlink individual agent .md files
# ═════════════════════════════════════════════════════════════
sync_claude() {
  echo ""
  echo -e "${BOLD}── Syncing to Claude Code ──${NC}"

  local claude_agents_dir="$CLAUDE_DIR/agents"
  mkdir -p "$claude_agents_dir"

  if $REFRESH; then
    info "Cleaning existing symlinks in $claude_agents_dir"
    purge_symlinks_in "$claude_agents_dir"
  fi

  local build_dir="$AGENTS_HOME/agents/claude"
  local count=0
  for agent_file in "${RESOLVED_AGENTS[@]}"; do
    [[ -f "$agent_file" ]] || continue
    local basename
    basename=$(basename "$agent_file")
    local built_file="$build_dir/$basename"
    [[ -f "$built_file" ]] || continue
    make_link "$built_file" "$claude_agents_dir/$basename"
    count=$((count + 1))
  done
  log "Claude: symlinked $count agent files → $claude_agents_dir/"

  sync_skills_to "$CLAUDE_DIR/skills" "claude" "Claude"
  sync_rules_to "$CLAUDE_DIR/rules" "claude" "Claude"
  sync_workflows_to "$CLAUDE_DIR/workflows" "claude" "Claude"
  sync_hooks_to "$CLAUDE_DIR/hooks" "claude" "Claude"
  sync_mcp_to "claude" "Claude"
}

# ═════════════════════════════════════════════════════════════
# GEMINI CLI — generate concatenated GEMINI.md
# ═════════════════════════════════════════════════════════════
sync_gemini() {
  echo ""
  echo -e "${BOLD}── Syncing to Gemini CLI ──${NC}"

  if [[ ! -d "$GEMINI_DIR" ]]; then
    warn "Gemini directory not found at $GEMINI_DIR — creating it"
    mkdir -p "$GEMINI_DIR"
  fi

  local output="$GEMINI_DIR/GEMINI.md"
  local marker="<!-- MANAGED BY ~/ai-management install.sh sync — DO NOT EDIT MANUALLY -->"
  local build_dir="$AGENTS_HOME/agents/gemini"

  if $DRY_RUN; then
    info "[dry-run] Would generate $output"
    return
  fi

  {
    echo "$marker"
    echo ""
    echo "# Custom Instructions"
    echo ""
    echo "> Auto-generated from \`~/ai-management/agents/\` by \`install.sh sync\`"
    echo "> Last synced: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo ""

    # ── Global rules ──
    if [[ ${#RESOLVED_RULES[@]} -gt 0 ]]; then
      local rules_build_dir="$AGENTS_HOME/rules/gemini"
      echo "## Global Rules"
      echo ""
      for rule_file in "${RESOLVED_RULES[@]}"; do
        [[ -f "$rule_file" ]] || continue
        local rule_basename
        rule_basename=$(basename "$rule_file")
        local built_rule="$rules_build_dir/$rule_basename"
        [[ -f "$built_rule" ]] && rule_file="$built_rule"
        echo "### $(basename "$rule_file" .md)"
        echo ""
        cat "$rule_file"
        echo ""
      done
      echo "---"
      echo ""
    fi

    # ── Agent definitions ──
    echo "## Available Agent Personas"
    echo ""
    echo "When asked to work as a specific agent or persona, adopt the matching instructions below."
    echo ""

    for agent_file in "${RESOLVED_AGENTS[@]}"; do
      [[ -f "$agent_file" ]] || continue
      local basename
      basename=$(basename "$agent_file")
      local built_file="$build_dir/$basename"
      [[ -f "$built_file" ]] || continue
      local name
      name=$(basename "$built_file" .md)
      echo "---"
      echo ""
      echo "### Agent: $name"
      echo ""
      cat "$built_file"
      echo ""
    done

    # ── Workflows ──
    if [[ ${#RESOLVED_WORKFLOWS[@]} -gt 0 ]]; then
      local wf_build_dir="$AGENTS_HOME/workflows/gemini"
      echo "---"
      echo ""
      echo "## Workflows"
      echo ""
      for wf_file in "${RESOLVED_WORKFLOWS[@]}"; do
        [[ -f "$wf_file" ]] || continue
        local wf_basename
        wf_basename=$(basename "$wf_file")
        local built_wf="$wf_build_dir/$wf_basename"
        [[ -f "$built_wf" ]] && wf_file="$built_wf"
        echo "### $(basename "$wf_file" .md)"
        echo ""
        cat "$wf_file"
        echo ""
      done
    fi

    # ── Skills (embedded — Gemini has no native skills directory) ──
    if [[ ${#RESOLVED_SKILLS[@]} -gt 0 ]]; then
      local skills_build_dir="$AGENTS_HOME/skills/gemini"
      local has_skills=false
      for skill_dir in "${RESOLVED_SKILLS[@]}"; do
        [[ -d "$skill_dir" ]] || continue
        local skill_name
        skill_name=$(basename "$skill_dir")
        local use_dir="$skill_dir"
        [[ -d "$skills_build_dir/$skill_name" ]] && use_dir="$skills_build_dir/$skill_name"
        local skill_md=""
        [[ -f "$use_dir/SKILL.md" ]] && skill_md="$use_dir/SKILL.md"
        [[ -f "$use_dir/skill.md" ]] && skill_md="$use_dir/skill.md"
        [[ -n "$skill_md" ]] || continue
        if ! $has_skills; then
          echo "---"
          echo ""
          echo "## Skills"
          echo ""
          echo "The following skills are available. Use their instructions when relevant."
          echo ""
          has_skills=true
        fi
        echo "### Skill: $(basename "$skill_dir")"
        echo ""
        cat "$skill_md"
        echo ""
      done
    fi

  } > "$output"

  local size
  size=$(wc -c < "$output" | tr -d ' ')
  log "Gemini: generated $output ($(( size / 1024 ))KB)"

  sync_mcp_to "gemini" "Gemini"
}

# ═════════════════════════════════════════════════════════════
# PURGE — remove all managed files from target directories
# ═════════════════════════════════════════════════════════════
purge_copilot() {
  echo ""
  echo -e "${BOLD}── Purging Copilot ──${NC}"
  local dirs=(
    "$COPILOT_AGENTS_DIR"
    "$TARGET_ROOT/.copilot/skills"
    "$TARGET_ROOT/.copilot/instructions"
    "$TARGET_ROOT/.copilot/workflows"
    "$TARGET_ROOT/.copilot/hooks"
  )
  if $DRY_RUN; then
    for d in "${dirs[@]}"; do
      [[ -d "$d" ]] && info "[dry-run] Would purge symlinks in $d"
    done
    [[ -f "$TARGET_ROOT/.copilot/mcp.json" ]] && info "[dry-run] Would remove $TARGET_ROOT/.copilot/mcp.json"
    return
  fi
  for d in "${dirs[@]}"; do
    purge_symlinks_in "$d"
  done
  rm -f "$TARGET_ROOT/.copilot/mcp.json" 2>/dev/null || true
  log "Copilot: purged all managed files"
}

purge_codex() {
  echo ""
  echo -e "${BOLD}── Purging Codex ──${NC}"
  local dirs=(
    "$CODEX_AGENTS_DIR"
    "$CODEX_DIR/skills"
    "$CODEX_DIR/instructions"
    "$CODEX_DIR/workflows"
    "$CODEX_DIR/hooks"
  )
  if $DRY_RUN; then
    for d in "${dirs[@]}"; do
      [[ -d "$d" ]] && info "[dry-run] Would purge symlinks in $d"
    done
    [[ -f "$CODEX_DIR/mcp-servers.json" ]] && info "[dry-run] Would remove $CODEX_DIR/mcp-servers.json"
    return
  fi
  for d in "${dirs[@]}"; do
    purge_symlinks_in "$d"
  done
  rm -f "$CODEX_DIR/AGENTS.md" 2>/dev/null || true
  rm -f "$CODEX_DIR/mcp-servers.json" 2>/dev/null || true
  log "Codex: purged all managed files"
}

purge_claude() {
  echo ""
  echo -e "${BOLD}── Purging Claude ──${NC}"
  local dirs=(
    "$CLAUDE_DIR/agents"
    "$CLAUDE_DIR/skills"
    "$CLAUDE_DIR/rules"
    "$CLAUDE_DIR/workflows"
    "$CLAUDE_DIR/hooks"
  )
  if $DRY_RUN; then
    for d in "${dirs[@]}"; do
      [[ -d "$d" ]] && info "[dry-run] Would purge symlinks in $d"
    done
    [[ -f "$CLAUDE_DIR/mcp.json" ]] && info "[dry-run] Would remove $CLAUDE_DIR/mcp.json"
    return
  fi
  for d in "${dirs[@]}"; do
    purge_symlinks_in "$d"
  done
  rm -f "$CLAUDE_DIR/mcp.json" 2>/dev/null || true
  log "Claude: purged all managed files"
}

purge_gemini() {
  echo ""
  echo -e "${BOLD}── Purging Gemini ──${NC}"
  local output="$GEMINI_DIR/GEMINI.md"
  if [[ ! -f "$output" ]]; then
    info "Nothing to purge — $output does not exist"
    return
  fi
  if $DRY_RUN; then
    info "[dry-run] Would remove $output"
    return
  fi
  rm -f "$output"
  log "Gemini: purged $output"
}
# ── Sync Helpers ──────────────────────────────────────────────
sync_usage() {
  echo "Usage: $(basename "$0") sync [targets] [flags]"
  echo ""
  echo "Targets: copilot codex claude gemini"
  echo ""
  echo "Flags:"
  echo "  -g, --global             Sync globally (~/) instead of the current project"
  echo "      --dry-run            Show what would happen"
  echo "      --refresh            Remove synced symlinks before re-syncing"
  echo "      --purge              Remove all managed files from targets (no re-sync)"
  echo "      --no-backup          Skip automatic backup before changes"
  echo "      --restore [file.zip] Restore interactively or from a specific backup file"
  echo "      --restore-latest     Restore the most recent backup"
  echo "      --pull               Download latest content from GitHub"
  echo "      --group <name>       Sync only items in the named group"
  echo "      --template <name>    Sync items defined in a template"
  echo "  -h, --help               Show this help"
  echo ""
  echo "Examples:"
  echo "  $(basename "$0") sync"
  echo "  $(basename "$0") sync -g"
  echo "  $(basename "$0") sync copilot codex --dry-run"
  echo "  $(basename "$0") sync --group default --refresh"
  echo "  $(basename "$0") sync --template web-development"
}

parse_sync_args() {
  sync_reset_state

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run)        DRY_RUN=true ;;
      --refresh)        REFRESH=true ;;
      --purge)          PURGE=true ;;
      --no-backup)      BACKUP=false ;;
      --pull)           PULL=true ;;
      -g|--global)      GLOBAL_MODE=true ;;
      --group)
        if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
          err "Error: --group requires a name"
          exit 1
        fi
        SELECTED_GROUPS+=("$2")
        shift
        ;;
      --template)
        if [[ -z "${2:-}" || "${2:-}" == --* ]]; then
          err "Error: --template requires a name"
          exit 1
        fi
        TEMPLATE="$2"
        shift
        ;;
      --restore-latest) RESTORE_LATEST=true ;;
      --restore)
        RESTORE=true
        if [[ "${2:-}" != "" && "${2:-}" != --* && ! "${2:-}" =~ ^(copilot|codex|claude|gemini)$ ]]; then
          RESTORE_FILE="$2"
          shift
        fi
        ;;
      copilot|codex|claude|gemini)
        TARGETS+=("$1")
        ;;
      --help|-h)
        sync_usage
        exit 0
        ;;
      *)
        err "Unknown sync argument: $1"
        exit 1
        ;;
    esac
    shift
  done

  if [[ ${#TARGETS[@]} -eq 0 ]]; then
    TARGETS=(copilot codex claude gemini)
  fi

  return 0
}

sync_init_runtime() {
  if [[ "$GLOBAL_MODE" == true ]]; then
    TARGET_ROOT="$HOME"
  else
    TARGET_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
  fi

  COPILOT_AGENTS_DIR="$TARGET_ROOT/.copilot/agents"
  CODEX_DIR="$TARGET_ROOT/.codex"
  CODEX_AGENTS_DIR="$TARGET_ROOT/.codex/agents"
  CLAUDE_DIR="$TARGET_ROOT/.claude"
  GEMINI_DIR="$TARGET_ROOT/.gemini"

  if [[ "$GLOBAL_MODE" == true ]]; then
    info "Mode: ${BOLD}global${NC} (target: $TARGET_ROOT)"
  else
    info "Mode: ${BOLD}project${NC} (target: $TARGET_ROOT)"
  fi
}

sync_apply_template_file() {
  local template_file="$1"
  local current_section=""

  while IFS= read -r line; do
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" =~ ^\[([a-z]+)\]$ ]]; then
      current_section="${BASH_REMATCH[1]}"
      continue
    fi
    if [[ -n "$current_section" ]]; then
      case "$current_section" in
        groups)    SELECTED_GROUPS+=("$line") ;;
        agents)    _GRP_AGENTS+=("$line") ;;
        skills)    _GRP_SKILLS+=("$line") ;;
        rules)     _GRP_RULES+=("$line") ;;
        workflows) _GRP_WORKFLOWS+=("$line") ;;
        hooks)     _GRP_HOOKS+=("$line") ;;
        mcp)       _GRP_MCP+=("$line") ;;
        *)         warn "Unknown template section: [$current_section]" ;;
      esac
    fi
  done < "$template_file"
}

sync_resolve_selection() {
  _GRP_AGENTS=()
  _GRP_SKILLS=()
  _GRP_RULES=()
  _GRP_WORKFLOWS=()
  _GRP_HOOKS=()
  _GRP_MCP=()

  if [[ -n "$TEMPLATE" ]]; then
    TEMPLATE_FILE="$AGENTS_HOME/templates/${TEMPLATE}.template"
    if [[ ! -f "$TEMPLATE_FILE" ]]; then
      err "Template file not found: $TEMPLATE_FILE"
      exit 1
    fi
    info "Applying template: ${BOLD}$TEMPLATE${NC}"
    sync_apply_template_file "$TEMPLATE_FILE"

    if [[ "$GLOBAL_MODE" == false && "$DRY_RUN" == false ]]; then
      echo "$TEMPLATE" > "$TARGET_ROOT/.ai-management"
      log "Saved template reference → $TARGET_ROOT/.ai-management"
    fi
  fi

  if [[ -z "$TEMPLATE" && ${#SELECTED_GROUPS[@]} -eq 0 ]]; then
    if [[ "$GLOBAL_MODE" == false && -f "$TARGET_ROOT/.ai-management" ]]; then
      _saved_template="$(head -1 "$TARGET_ROOT/.ai-management" | tr -d '[:space:]')"
      if [[ -n "$_saved_template" ]]; then
        TEMPLATE_FILE="$AGENTS_HOME/templates/${_saved_template}.template"
        if [[ -f "$TEMPLATE_FILE" ]]; then
          info "Using project template: ${BOLD}$_saved_template${NC}"
          sync_apply_template_file "$TEMPLATE_FILE"
        fi
      fi
    fi
  fi

  [[ ${#SELECTED_GROUPS[@]} -eq 0 ]] && SELECTED_GROUPS=(default)

  for group_name in "${SELECTED_GROUPS[@]}"; do
    local group_file="$AGENTS_HOME/groups/${group_name}.group"
    if [[ ! -f "$group_file" ]]; then
      err "Group file not found: $group_file"
      exit 1
    fi
    info "Loading group: ${BOLD}$group_name${NC}"
    parse_group_file "$group_file"
  done

  RESOLVED_AGENTS=()
  RESOLVED_SKILLS=()
  RESOLVED_RULES=()
  RESOLVED_WORKFLOWS=()
  RESOLVED_HOOKS=()
  RESOLVED_MCP=()

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_AGENTS[@]}" && RESOLVED_AGENTS+=("$p")
  done < <(resolve_section agents "$AGENTS_HOME/agents" "${_GRP_AGENTS[@]+"${_GRP_AGENTS[@]}"}")

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_SKILLS[@]}" && RESOLVED_SKILLS+=("$p")
  done < <(resolve_section skills "$AGENTS_HOME/skills" "${_GRP_SKILLS[@]+"${_GRP_SKILLS[@]}"}")

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_RULES[@]}" && RESOLVED_RULES+=("$p")
  done < <(resolve_section rules "$AGENTS_HOME/rules" "${_GRP_RULES[@]+"${_GRP_RULES[@]}"}")

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_WORKFLOWS[@]}" && RESOLVED_WORKFLOWS+=("$p")
  done < <(resolve_section workflows "$AGENTS_HOME/workflows" "${_GRP_WORKFLOWS[@]+"${_GRP_WORKFLOWS[@]}"}")

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_HOOKS[@]}" && RESOLVED_HOOKS+=("$p")
  done < <(resolve_section hooks "$AGENTS_HOME/hooks" "${_GRP_HOOKS[@]+"${_GRP_HOOKS[@]}"}")

  while IFS= read -r p; do
    [[ -n "$p" ]] && ! array_contains "$p" "${RESOLVED_MCP[@]}" && RESOLVED_MCP+=("$p")
  done < <(resolve_section mcp "$AGENTS_HOME/mcp" "${_GRP_MCP[@]+"${_GRP_MCP[@]}"}")

  info "Group resolved: ${BOLD}${#RESOLVED_AGENTS[@]}${NC} agents, ${#RESOLVED_SKILLS[@]} skills, ${#RESOLVED_RULES[@]} rules, ${#RESOLVED_WORKFLOWS[@]} workflows, ${#RESOLVED_HOOKS[@]} hooks, ${#RESOLVED_MCP[@]} mcp"
}

sync_command() {
  parse_sync_args "$@"
  sync_init_runtime

  if $PULL; then
    pull_from_github
  fi

  setup_ai_mgmt_dir

  if [[ ! -d "$AGENTS_HOME/agents" ]]; then
    err "No agents directory found at $AGENTS_HOME/agents"
    echo ""
    echo "  Run with --pull to download content from GitHub:"
    echo "    $0 sync --pull"
    echo ""
    echo "  Make sure AI_MANAGEMENT_REPO is set to your GitHub repository."
    exit 1
  fi

  local agent_count
  agent_count=$(find -L "$AGENTS_HOME/agents" -name '*.md' -maxdepth 1 2>/dev/null | wc -l | tr -d ' ')
  info "Found ${BOLD}$agent_count${NC} agent files in $AGENTS_HOME/agents/"

  sync_resolve_selection

  echo -e "${BOLD}🔄 AI Management Sync — $(date '+%Y-%m-%d %H:%M:%S')${NC}"
  $DRY_RUN && echo -e "${YELLOW}(dry-run mode)${NC}"

  if $RESTORE || $RESTORE_LATEST; then
    for target in "${TARGETS[@]}"; do
      restore_target "$target"
    done
    echo ""
    log "Restore complete."
    return 0
  fi

  if $BACKUP; then
    echo ""
    echo -e "${BOLD}── Backing up existing managed files ──${NC}"
    for target in "${TARGETS[@]}"; do
      while IFS= read -r p; do
        [[ -n "$p" ]] && backup_path "$target" "$p"
      done < <(managed_paths_for "$target")
    done
  fi

  if $PURGE; then
    echo -e "${RED}(purge mode — removing all managed files from targets)${NC}"
    for target in "${TARGETS[@]}"; do
      case "$target" in
        copilot) purge_copilot ;;
        codex)   purge_codex ;;
        claude)  purge_claude ;;
        gemini)  purge_gemini ;;
      esac
    done
    if ! $REFRESH; then
      echo ""
      log "Purge complete."
      return 0
    fi
    echo ""
    info "Continuing with fresh sync…"
  fi

  local harnesses
  harnesses=$(IFS=,; echo "${TARGETS[*]}")
  build_all "$harnesses"

  for target in "${TARGETS[@]}"; do
    case "$target" in
      copilot) sync_copilot ;;
      codex)   sync_codex ;;
      claude)  sync_claude ;;
      gemini)  sync_gemini ;;
    esac
  done

  echo ""
  log "Sync complete."
}

# ═══════════════════════════════════════════════════════════════
# Install CLI Interface
# ═══════════════════════════════════════════════════════════════
install_usage() {
  echo "Usage: $(basename "$0") [options]"
  echo "       $(basename "$0") sync [targets] [flags]"
  echo ""
  echo "Interactive installer for AI Management content."
  echo ""
  echo "Options:"
  echo "  --list                       List all available skills"
  echo "  --list-groups                List all groups"
  echo "  --list-templates             List all templates"
  echo "  --installed                  Show installed items (all types)"
  echo ""
  echo "  Default install:"
  echo "  --install                    Install the default group (core agents, skills, etc.)"
  echo ""
  echo "  Individual install:"
  echo "  --install-agent <names>      Install agents (comma-separated)"
  echo "  --install-skill <names>      Install skills (comma-separated)"
  echo "  --install-rule <names>       Install rules (comma-separated)"
  echo "  --install-workflow <names>   Install workflows (comma-separated)"
  echo "  --install-hook <names>       Install hooks (comma-separated)"
  echo "  --install-mcp <names>        Install MCP servers (comma-separated)"
  echo ""
  echo "  Group install:"
  echo "  --install-group <name>         Install everything in a group"
  echo "  --install-group-agents <name>  Install only agents from a group"
  echo "  --install-group-skills <name>  Install only skills from a group"
  echo "  --install-group-rules <name>   Install only rules from a group"
  echo "  --install-group-workflows <name>"
  echo "  --install-group-hooks <name>"
  echo "  --install-group-mcp <name>"
  echo ""
  echo "  Template install:"
  echo "  --template <name>            Install a template (groups + items) to current project"
  echo "  --template <name> --global   Install a template globally"
  echo ""
  echo "  Install all:"
  echo "  --install-all                Install everything (all types)"
  echo "  --install-all-agents         Install all agents"
  echo "  --install-all-skills         Install all skills"
  echo "  --install-all-rules          Install all rules"
  echo "  --install-all-workflows      Install all workflows"
  echo "  --install-all-hooks          Install all hooks"
  echo "  --install-all-mcp            Install all MCP servers"
  echo ""
  echo "  Uninstall:"
  echo "  --uninstall-agent <names>    Uninstall agents (comma-separated)"
  echo "  --uninstall-skill <names>    Uninstall skills (comma-separated)"
  echo "  --uninstall-rule <names>     Uninstall rules (comma-separated)"
  echo "  --uninstall-workflow <names> Uninstall workflows (comma-separated)"
  echo "  --uninstall-hook <names>     Uninstall hooks (comma-separated)"
  echo "  --uninstall-mcp <names>      Uninstall MCP servers (comma-separated)"
  echo ""
  echo "  Sync / deploy:"
  echo "  sync [targets] [flags]       Deploy installed/template/group content to harnesses"
  echo "    targets: copilot codex claude gemini"
  echo "    flags:   -g/--global, --dry-run, --refresh, --purge, --no-backup,"
  echo "             --restore [file], --restore-latest, --pull, --group, --template"
  echo ""
  echo "  -h, --help                   Show this help"
  echo ""
  echo "Examples:"
  echo "  $(basename "$0") --install                           # install defaults"
  echo "  $(basename "$0") --install-skill code-review,debugging"
  echo "  $(basename "$0") --install-group core-development"
  echo "  $(basename "$0") --template web-development          # apply template to project"
  echo "  $(basename "$0") --install-all-skills"
  echo "  $(basename "$0") sync --template web-development"
  echo ""
  echo "Without arguments, launches the interactive menu."
}

install_cli() {
  case "$1" in
    -h|--help)
      install_usage
      ;;
    --list)
      get_all_skills
      ;;
    --list-groups)
      for f in "$GROUPS_DIR"/*.group; do
        [[ -f "$f" ]] || continue
        grep -q '^\[skills\]' "$f" || continue
        _name=$(basename "$f" .group)
        _desc=$(group_description "$f")
        _count=$(parse_group "$f" | wc -l | tr -d ' ')
        printf "%-25s (%s skills)  %s\n" "$_name" "$_count" "$_desc"
      done
      ;;
    --installed)
      _found=0
      for _type in agents skills rules workflows hooks mcp; do
        load_installed_type "${_type}"
        if [[ ${#INSTALLED_ITEMS[@]} -gt 0 ]]; then
          echo "${_type}:"
          for s in "${INSTALLED_ITEMS[@]}"; do echo "  $s"; done
          _found=1
        fi
      done
      [[ $_found -eq 0 ]] && echo "Nothing installed"
      ;;
    --install)
      _grp_file="$GROUPS_DIR/default.group"
      [[ -f "$_grp_file" ]] || { err "Default group not found"; exit 1; }
      info "Installing default group..."
      for _type in agents skills rules workflows hooks mcp; do
        _items=()
        while IFS= read -r s; do
          [[ -n "$s" ]] && _items+=("$s")
        done < <(parse_group_section "$_grp_file" "$_type")
        if [[ ${#_items[@]} -gt 0 ]]; then
          install_type "$_type" "${_items[@]}"
        fi
      done
      ;;
    --install-agent|--install-skill|--install-rule|--install-workflow|--install-hook|--install-mcp)
      _type="${1#--install-}"
      case "$_type" in
        agent) _type="agents" ;;
        skill) _type="skills" ;;
        rule) _type="rules" ;;
        workflow) _type="workflows" ;;
        hook) _type="hooks" ;;
      esac
      shift
      [[ $# -eq 0 ]] && { err "Provide names (comma-separated)"; exit 1; }
      IFS=',' read -ra _items <<< "$1"
      install_type "$_type" "${_items[@]}"
      ;;
    --install-group)
      shift
      [[ $# -eq 0 ]] && { err "Provide group name"; exit 1; }
      _grp_file="$GROUPS_DIR/$1.group"
      [[ -f "$_grp_file" ]] || { err "Group not found: $1"; exit 1; }
      for _type in agents skills rules workflows hooks mcp; do
        _items=()
        while IFS= read -r s; do
          [[ -n "$s" ]] && _items+=("$s")
        done < <(parse_group_section "$_grp_file" "$_type")
        if [[ ${#_items[@]} -gt 0 ]]; then
          install_type "$_type" "${_items[@]}"
        fi
      done
      ;;
    --install-group-*)
      _type="${1#--install-group-}"
      shift
      [[ $# -eq 0 ]] && { err "Provide group name"; exit 1; }
      case "$_type" in
        agents|skills|rules|workflows|hooks|mcp) ;;
        *) err "Unknown type: $_type (valid: agents, skills, rules, workflows, hooks, mcp)"; exit 1 ;;
      esac
      _grp_file="$GROUPS_DIR/$1.group"
      [[ -f "$_grp_file" ]] || { err "Group not found: $1"; exit 1; }
      _items=()
      while IFS= read -r s; do
        [[ -n "$s" ]] && _items+=("$s")
      done < <(parse_group_section "$_grp_file" "$_type")
      if [[ ${#_items[@]} -eq 0 ]]; then
        warn "No $_type found in group: $1"
        exit 0
      fi
      install_type "$_type" "${_items[@]}"
      ;;
    --install-all)
      for _type in agents skills rules workflows hooks mcp; do
        _all=()
        while IFS= read -r s; do
          [[ -n "$s" ]] && _all+=("$s")
        done < <(get_all_type "$_type")
        if [[ ${#_all[@]} -gt 0 ]]; then
          install_type "$_type" "${_all[@]}"
        fi
      done
      ;;
    --install-all-*)
      _type="${1#--install-all-}"
      case "$_type" in
        agents|skills|rules|workflows|hooks|mcp) ;;
        *) err "Unknown type: $_type (valid: agents, skills, rules, workflows, hooks, mcp)"; exit 1 ;;
      esac
      _all=()
      while IFS= read -r s; do
        [[ -n "$s" ]] && _all+=("$s")
      done < <(get_all_type "$_type")
      if [[ ${#_all[@]} -eq 0 ]]; then
        warn "No $_type found"
        exit 0
      fi
      install_type "$_type" "${_all[@]}"
      ;;
    --uninstall-agent|--uninstall-skill|--uninstall-rule|--uninstall-workflow|--uninstall-hook|--uninstall-mcp)
      _type="${1#--uninstall-}"
      case "$_type" in
        agent) _type="agents" ;;
        skill) _type="skills" ;;
        rule) _type="rules" ;;
        workflow) _type="workflows" ;;
        hook) _type="hooks" ;;
      esac
      shift
      [[ $# -eq 0 ]] && { err "Provide names (comma-separated)"; exit 1; }
      load_installed_type "$_type"
      IFS=',' read -ra to_remove <<< "$1"
      for r in "${to_remove[@]}"; do
        r="$(echo "$r" | tr -d ' ')"
        INSTALLED_ITEMS=($(toggle_selection "$r" "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"))
        ok "Uninstalled ${_type%s}: $r"
      done
      save_installed_type "$_type"
      ;;
    --list-templates)
      for f in "$TEMPLATES_DIR"/*.template; do
        [[ -f "$f" ]] || continue
        _name=$(basename "$f" .template)
        _desc=$(head -1 "$f" | sed 's/^# //')
        printf "%-25s %s\n" "$_name" "$_desc"
      done
      ;;
    --template)
      shift
      [[ $# -eq 0 ]] && { err "Provide template name"; exit 1; }
      _tpl_name="$1"
      _tpl_file="$TEMPLATES_DIR/${_tpl_name}.template"
      [[ -f "$_tpl_file" ]] || { err "Template not found: $_tpl_name"; exit 1; }
      info "Installing template: $_tpl_name"
      _TPL_SECTION=""
      while IFS= read -r line; do
        line="${line%%#*}"
        line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [[ -z "$line" ]] && continue
        if [[ "$line" == "["*"]" ]]; then
          _TPL_SECTION="${line:1:${#line}-2}"
          continue
        fi
        if [[ -n "$_TPL_SECTION" ]]; then
          case "$_TPL_SECTION" in
            groups)
              _grp_file="$GROUPS_DIR/${line}.group"
              [[ -f "$_grp_file" ]] || { warn "Group not found in template: $line"; continue; }
              for _type in agents skills rules workflows hooks mcp; do
                _items=()
                while IFS= read -r s; do
                  [[ -n "$s" ]] && _items+=("$s")
                done < <(parse_group_section "$_grp_file" "$_type")
                if [[ ${#_items[@]} -gt 0 ]]; then
                  install_type "$_type" "${_items[@]}"
                fi
              done
              ;;
            agents|skills|rules|workflows|hooks|mcp)
              install_type "$_TPL_SECTION" "$line"
              ;;
          esac
        fi
      done < "$_tpl_file"
      _global=false
      for _a in "$@"; do [[ "$_a" == "--global" || "$_a" == "-g" ]] && _global=true; done
      if [[ "$_global" == false ]]; then
        _project_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
        echo "$_tpl_name" > "$_project_root/.ai-management"
        ok "Saved template → $_project_root/.ai-management"
      fi
      info "Run ${CYAN}$(basename "$0") sync --template $_tpl_name${NC} to deploy"
      ;;
    *)
      err "Unknown option: $1"
      install_usage
      exit 1
      ;;
  esac
}

if [[ $# -eq 0 ]]; then
  main_menu
  exit 0
fi

if [[ "$1" == "sync" ]]; then
  shift
  sync_command "$@"
  exit 0
fi

install_cli "$@"
