#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# AI Management Content Installer
# Interactive menu for selecting which content/groups to install
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$SCRIPT_DIR/skills"
GROUPS_DIR="$SCRIPT_DIR/groups"
AI_MGMT_HOME="${AI_MANAGEMENT_HOME:-$HOME/ai-management}"
INSTALLED_DIR="$AI_MGMT_HOME/installed"
INSTALLED_FILE="$INSTALLED_DIR/skills.conf"

# ── Colors ────────────────────────────────────────────────────
BOLD='\033[1m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ── Helpers ───────────────────────────────────────────────────
info()  { echo -e "  ${CYAN}→${NC} $*"; }
ok()    { echo -e "  ${GREEN}✓${NC} $*"; }
warn()  { echo -e "  ${YELLOW}⚠${NC} $*"; }
err()   { echo -e "  ${RED}✗${NC} $*"; }

# ── Load installed items for a content type ───────────────────
# Migrate legacy installed-skills.conf if present
_migrate_legacy() {
  local legacy="$AI_MGMT_HOME/installed-skills.conf"
  if [[ -f "$legacy" && ! -f "$INSTALLED_DIR/skills.conf" ]]; then
    mkdir -p "$INSTALLED_DIR"
    cp "$legacy" "$INSTALLED_DIR/skills.conf"
    rm -f "$legacy"
  fi
}
_migrate_legacy

load_installed() {
  load_installed_type "skills"
}

load_installed_type() {
  local type="$1"
  local conf="$INSTALLED_DIR/${type}.conf"
  INSTALLED_ITEMS=()
  if [[ -f "$conf" ]]; then
    while IFS= read -r line; do
      line="${line%%#*}"
      line="${line// /}"
      [[ -n "$line" ]] && INSTALLED_ITEMS+=("$line")
    done < "$conf"
  fi
  # Keep INSTALLED_SKILLS in sync for backward compat
  if [[ "$type" == "skills" ]]; then
    INSTALLED_SKILLS=("${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}")
  fi
}

is_installed() {
  local item="$1"
  for s in "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"; do
    [[ "$s" == "$item" ]] && return 0
  done
  return 1
}

save_installed() {
  save_installed_type "skills"
}

save_installed_type() {
  local type="$1"
  local conf="$INSTALLED_DIR/${type}.conf"
  mkdir -p "$INSTALLED_DIR"
  printf "# AI Management installed %s\n# Auto-generated by install.sh\n" "$type" > "$conf"
  for s in "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"; do
    echo "$s" >> "$conf"
  done
  # Keep INSTALLED_SKILLS in sync
  if [[ "$type" == "skills" ]]; then
    INSTALLED_SKILLS=("${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}")
  fi
}

# ── Discover available skills ─────────────────────────────────
get_all_skills() {
  get_all_type "skills"
}

# ── Discover all items for any content type ───────────────────
HARNESS_DIRS="claude codex copilot gemini __pycache__ backups"

get_all_type() {
  local type="$1"
  local type_dir="$SCRIPT_DIR/$type"
  local -a items=()

  [[ -d "$type_dir" ]] || { return 0; }

  # Skills/hooks use subdirectories; agents/rules/workflows/mcp use .md files
  case "$type" in
    skills)
      for d in "$type_dir"/*/; do
        [[ -d "$d" ]] || continue
        local name
        name=$(basename "$d")
        # Skip build output dirs
        local skip=0
        for h in $HARNESS_DIRS; do [[ "$name" == "$h" ]] && skip=1; done
        [[ $skip -eq 1 ]] && continue
        [[ -f "$d/SKILL.md" ]] || continue
        items+=("$name")
      done
      ;;
    hooks)
      for entry in "$type_dir"/*; do
        [[ -e "$entry" ]] || continue
        local name
        name=$(basename "$entry")
        local skip=0
        for h in $HARNESS_DIRS; do [[ "$name" == "$h" ]] && skip=1; done
        [[ $skip -eq 1 ]] && continue
        items+=("$name")
      done
      ;;
    *)
      # agents, rules, workflows, mcp — flat .md files
      for f in "$type_dir"/*.md; do
        [[ -f "$f" ]] || continue
        local name
        name=$(basename "$f" .md)
        items+=("$name")
      done
      ;;
  esac

  printf '%s\n' "${items[@]+"${items[@]}"}" | sort
}

# ── Parse a group file for its [skills] section ───────────────
parse_group() {
  parse_group_section "$1" "skills"
}

# ── Parse any section from a group file ───────────────────────
parse_group_section() {
  local group_file="$1"
  local section="$2"
  local -a items=()
  local in_section=0

  while IFS= read -r line; do
    line="${line%%#*}"
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -z "$line" ]] && continue

    # Section header
    if [[ "$line" == "["*"]" ]]; then
      if [[ "$line" == "[$section]" ]]; then
        in_section=1
      else
        in_section=0
      fi
      continue
    fi

    if [[ $in_section -eq 1 ]]; then
      # Wildcard means all items in that type's directory
      if [[ "$line" == "*" ]]; then
        local type_dir="$SCRIPT_DIR/$section"
        if [[ -d "$type_dir" ]]; then
          for d in "$type_dir"/*/; do
            [[ -d "$d" ]] || continue
            local basename_d
            basename_d=$(basename "$d")
            [[ "$basename_d" == "__pycache__" ]] && continue
            items+=("$basename_d")
          done
        fi
      else
        items+=("$line")
      fi
    fi
  done < "$group_file"

  printf '%s\n' "${items[@]+"${items[@]}"}" | sort -u
}

# ── Get group description (first comment line) ────────────────
group_description() {
  head -1 "$1" | sed 's/^# //'
}

# ── Get skill description from SKILL.md frontmatter ───────────
skill_description() {
  local skill_dir="$SKILLS_DIR/$1"
  [[ -f "$skill_dir/SKILL.md" ]] || return
  # Extract description from YAML frontmatter
  sed -n '/^---$/,/^---$/p' "$skill_dir/SKILL.md" | grep -m1 "^description:" | sed "s/^description:[[:space:]]*//;s/^['\"]//;s/['\"]$//" | head -c 70
}

# ── Toggle selection in array ─────────────────────────────────
toggle_selection() {
  local item="$1"
  shift
  local -a arr=("$@")
  local found=false
  local -a new_arr=()

  for s in "${arr[@]+"${arr[@]}"}"; do
    if [[ "$s" == "$item" ]]; then
      found=true
    else
      new_arr+=("$s")
    fi
  done

  if ! $found; then
    new_arr+=("$item")
  fi

  printf '%s\n' "${new_arr[@]+"${new_arr[@]}"}"
}

is_in_array() {
  local item="$1"
  shift
  for s in "$@"; do
    [[ "$s" == "$item" ]] && return 0
  done
  return 1
}

# ═══════════════════════════════════════════════════════════════
# Interactive Menus
# ═══════════════════════════════════════════════════════════════

show_group_menu() {
  local -a selected_groups=()
  local -a groups=()
  local -a group_files=()

  for f in "$GROUPS_DIR"/*.group; do
    [[ -f "$f" ]] || continue
    local name
    name=$(basename "$f" .group)
    [[ "$name" == "all" ]] && continue
    # Only show groups that have a [skills] section
    grep -q '^\[skills\]' "$f" || continue
    groups+=("$name")
    group_files+=("$f")
  done

  while true; do
    clear
    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}║       Select Skill Groups                    ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo ""

    local i=1
    for idx in "${!groups[@]}"; do
      local name="${groups[$idx]}"
      local desc
      desc=$(group_description "${group_files[$idx]}")
      local skill_count
      skill_count=$(parse_group "${group_files[$idx]}" | wc -l | tr -d ' ')
      local marker="  "
      if is_in_array "$name" "${selected_groups[@]+"${selected_groups[@]}"}"; then
        marker="${GREEN}✓ ${NC}"
      fi
      printf "  ${marker}${BLUE}%2d)${NC} %-25s ${YELLOW}(%s skills)${NC}  %s\n" "$i" "$name" "$skill_count" "$desc"
      i=$((i + 1))
    done

    echo ""
    printf "  ${GREEN}✓ ${BLUE} a)${NC} Select ALL groups\n"
    printf "  ${RED}✗ ${BLUE} n)${NC} Deselect all\n"
    echo ""
    echo -e "  ${BOLD}Selected: ${#selected_groups[@]} groups${NC}"
    echo ""
    echo -e "  Enter number to toggle, ${GREEN}a${NC}ll, ${RED}n${NC}one, ${CYAN}i${NC}nstall, or ${RED}q${NC}uit:"
    read -rp "  > " choice

    case "$choice" in
      q|Q) return 1 ;;
      a|A)
        selected_groups=("${groups[@]}")
        ;;
      n|N)
        selected_groups=()
        ;;
      i|I)
        if [[ ${#selected_groups[@]} -eq 0 ]]; then
          warn "No groups selected"
          sleep 1
          continue
        fi
        # Resolve all skills from selected groups
        local -a resolved=()
        for grp in "${selected_groups[@]}"; do
          local grp_file="$GROUPS_DIR/${grp}.group"
          while IFS= read -r s; do
            [[ -n "$s" ]] && resolved+=("$s")
          done < <(parse_group "$grp_file")
        done
        # Deduplicate
        SKILLS_TO_INSTALL=($(printf '%s\n' "${resolved[@]}" | sort -u))
        return 0
        ;;
      *)
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#groups[@]} )); then
          local grp_name="${groups[$((choice - 1))]}"
          selected_groups=($(toggle_selection "$grp_name" "${selected_groups[@]+"${selected_groups[@]}"}"))
        fi
        ;;
    esac
  done
}

show_individual_menu() {
  local -a all_skills=()
  while IFS= read -r s; do
    [[ -n "$s" ]] && all_skills+=("$s")
  done < <(get_all_skills)

  local -a selected_skills=()
  local page=0
  local page_size=20
  local total=${#all_skills[@]}
  local total_pages=$(( (total + page_size - 1) / page_size ))

  while true; do
    clear
    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}║       Select Individual Skills               ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo -e "  Page $((page + 1))/$total_pages  |  Selected: ${#selected_skills[@]}/$total"
    echo ""

    local start=$((page * page_size))
    local end=$((start + page_size))
    (( end > total )) && end=$total

    local i=$((start + 1))
    for (( idx=start; idx<end; idx++ )); do
      local name="${all_skills[$idx]}"
      local marker="  "
      local installed_marker=""
      if is_in_array "$name" "${selected_skills[@]+"${selected_skills[@]}"}"; then
        marker="${GREEN}✓ ${NC}"
      fi
      if is_installed "$name"; then
        installed_marker=" ${CYAN}[installed]${NC}"
      fi
      local desc
      desc=$(skill_description "$name" 2>/dev/null || echo "")
      if [[ ${#desc} -gt 55 ]]; then
        desc="${desc:0:52}..."
      fi
      printf "  ${marker}${BLUE}%2d)${NC} %-35s %s${installed_marker}\n" "$i" "$name" "$desc"
      i=$((i + 1))
    done

    echo ""
    echo -e "  ${CYAN}<${NC} prev | ${CYAN}>${NC} next | ${GREEN}a${NC}ll | ${RED}n${NC}one | ${CYAN}i${NC}nstall | ${RED}q${NC}uit"
    read -rp "  > " choice

    case "$choice" in
      q|Q) return 1 ;;
      "<"|p|P)
        (( page > 0 )) && page=$((page - 1))
        ;;
      ">"|n_page|N_page)
        (( page < total_pages - 1 )) && page=$((page + 1))
        ;;
      a|A)
        selected_skills=("${all_skills[@]}")
        ;;
      n|N)
        selected_skills=()
        ;;
      i|I)
        if [[ ${#selected_skills[@]} -eq 0 ]]; then
          warn "No skills selected"
          sleep 1
          continue
        fi
        SKILLS_TO_INSTALL=("${selected_skills[@]}")
        return 0
        ;;
      *)
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= total )); then
          local skill_name="${all_skills[$((choice - 1))]}"
          selected_skills=($(toggle_selection "$skill_name" "${selected_skills[@]+"${selected_skills[@]}"}"))
        elif [[ "$choice" =~ ^[0-9]+-[0-9]+$ ]]; then
          # Range selection: e.g. 1-10
          local range_start="${choice%-*}"
          local range_end="${choice#*-}"
          for (( r=range_start; r<=range_end && r<=total; r++ )); do
            local skill_name="${all_skills[$((r - 1))]}"
            if ! is_in_array "$skill_name" "${selected_skills[@]+"${selected_skills[@]}"}"; then
              selected_skills+=("$skill_name")
            fi
          done
        fi
        ;;
    esac
  done
}

# ═══════════════════════════════════════════════════════════════
# Installation
# ═══════════════════════════════════════════════════════════════

install_skills() {
  install_type "skills" "$@"
}

# ── Generic installer for any content type ────────────────────
install_type() {
  local type="$1"
  shift
  local -a items=("$@")
  local type_dir="$SCRIPT_DIR/$type"

  echo ""
  echo -e "${BOLD}── Installing ${#items[@]} ${type} ──${NC}"

  load_installed_type "$type"

  local count=0
  for item in "${items[@]}"; do
    # Check existence: directories (skills/) or files (agents/)
    if [[ -d "$type_dir/$item" ]] || [[ -f "$type_dir/${item}.md" ]] || [[ -f "$type_dir/$item" ]]; then
      if ! is_installed "$item"; then
        INSTALLED_ITEMS+=("$item")
      fi
      ok "$item"
      count=$((count + 1))
    else
      warn "${type%s} not found: $item"
    fi
  done

  save_installed_type "$type"
  echo ""
  ok "Installed $count ${type} → $INSTALLED_DIR/${type}.conf"
  echo ""
  info "Run ${CYAN}sync.sh${NC} to deploy to your harnesses"
}

# ═══════════════════════════════════════════════════════════════
# Uninstall
# ═══════════════════════════════════════════════════════════════

uninstall_menu() {
  load_installed

  if [[ ${#INSTALLED_SKILLS[@]} -eq 0 ]]; then
    warn "No skills installed"
    return
  fi

  echo ""
  echo -e "${BOLD}── Installed Skills ──${NC}"
  local i=1
  for s in "${INSTALLED_SKILLS[@]}"; do
    printf "  ${BLUE}%2d)${NC} %s\n" "$i" "$s"
    i=$((i + 1))
  done
  echo ""
  echo -e "  Enter numbers to uninstall (comma-separated), ${RED}a${NC}ll, or ${RED}q${NC}uit:"
  read -rp "  > " choice

  case "$choice" in
    q|Q) return ;;
    a|A)
      INSTALLED_SKILLS=()
      save_installed
      ok "Uninstalled all skills"
      ;;
    *)
      local -a new_installed=("${INSTALLED_SKILLS[@]}")
      IFS=',' read -ra nums <<< "$choice"
      for num in "${nums[@]}"; do
        num="$(echo "$num" | tr -d ' ')"
        if [[ "$num" =~ ^[0-9]+$ ]] && (( num >= 1 && num <= ${#INSTALLED_SKILLS[@]} )); then
          local skill="${INSTALLED_SKILLS[$((num - 1))]}"
          new_installed=($(toggle_selection "$skill" "${new_installed[@]}"))
          ok "Uninstalled: $skill"
        fi
      done
      INSTALLED_SKILLS=("${new_installed[@]+"${new_installed[@]}"}")
      save_installed
      ;;
  esac
}

# ═══════════════════════════════════════════════════════════════
# Main Menu
# ═══════════════════════════════════════════════════════════════

main_menu() {
  while true; do
    clear
    load_installed
    local installed_count=${#INSTALLED_SKILLS[@]}
    local total_count
    total_count=$(get_all_skills | wc -l | tr -d ' ')

    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       AI Management Installer                ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "  ${CYAN}$total_count${NC} skills available  |  ${GREEN}$installed_count${NC} installed"
    echo ""
    echo -e "  ${BLUE}1)${NC} Browse by ${BOLD}group${NC}        (categories of related skills)"
    echo -e "  ${BLUE}2)${NC} Browse ${BOLD}individual${NC}      (pick specific skills)"
    echo -e "  ${BLUE}3)${NC} Install ${GREEN}all${NC} skills"
    echo -e "  ${BLUE}4)${NC} ${RED}Uninstall${NC} skills"
    echo -e "  ${BLUE}5)${NC} Show installed"
    echo -e "  ${BLUE}q)${NC} Quit"
    echo ""
    read -rp "  > " choice

    case "$choice" in
      1)
        SKILLS_TO_INSTALL=()
        if show_group_menu; then
          install_skills "${SKILLS_TO_INSTALL[@]}"
          read -rp "  Press Enter to continue..."
        fi
        ;;
      2)
        SKILLS_TO_INSTALL=()
        if show_individual_menu; then
          install_skills "${SKILLS_TO_INSTALL[@]}"
          read -rp "  Press Enter to continue..."
        fi
        ;;
      3)
        local -a all=()
        while IFS= read -r s; do
          [[ -n "$s" ]] && all+=("$s")
        done < <(get_all_skills)
        install_skills "${all[@]}"
        read -rp "  Press Enter to continue..."
        ;;
      4)
        uninstall_menu
        read -rp "  Press Enter to continue..."
        ;;
      5)
        echo ""
        echo -e "${BOLD}── Installed Skills ──${NC}"
        if [[ $installed_count -eq 0 ]]; then
          info "No skills installed"
        else
          for s in "${INSTALLED_SKILLS[@]}"; do
            echo -e "  ${GREEN}✓${NC} $s"
          done
        fi
        echo ""
        read -rp "  Press Enter to continue..."
        ;;
      q|Q) break ;;
    esac
  done
}

# ═══════════════════════════════════════════════════════════════
# CLI Interface
# ═══════════════════════════════════════════════════════════════

usage() {
  echo "Usage: $(basename "$0") [options]"
  echo ""
  echo "Interactive installer for AI Management content."
  echo ""
  echo "Options:"
  echo "  --list                       List all available skills"
  echo "  --list-groups                List all groups"
  echo "  --list-templates             List all templates"
  echo "  --installed                  Show installed items (all types)"
  echo ""
  echo "  Default install:"
  echo "  --install                    Install the default group (core agents, skills, etc.)"
  echo ""
  echo "  Individual install:"
  echo "  --install-agent <names>      Install agents (comma-separated)"
  echo "  --install-skill <names>      Install skills (comma-separated)"
  echo "  --install-rule <names>       Install rules (comma-separated)"
  echo "  --install-workflow <names>   Install workflows (comma-separated)"
  echo "  --install-hook <names>       Install hooks (comma-separated)"
  echo "  --install-mcp <names>        Install MCP servers (comma-separated)"
  echo ""
  echo "  Group install:"
  echo "  --install-group <name>         Install everything in a group"
  echo "  --install-group-agents <name>  Install only agents from a group"
  echo "  --install-group-skills <name>  Install only skills from a group"
  echo "  --install-group-rules <name>   Install only rules from a group"
  echo "  --install-group-workflows <name>"
  echo "  --install-group-hooks <name>"
  echo "  --install-group-mcp <name>"
  echo ""
  echo "  Template install:"
  echo "  --template <name>            Install a template (groups + items) to current project"
  echo "  --template <name> --global   Install a template globally"
  echo ""
  echo "  Install all:"
  echo "  --install-all                Install everything (all types)"
  echo "  --install-all-agents         Install all agents"
  echo "  --install-all-skills         Install all skills"
  echo "  --install-all-rules          Install all rules"
  echo "  --install-all-workflows      Install all workflows"
  echo "  --install-all-hooks          Install all hooks"
  echo "  --install-all-mcp            Install all MCP servers"
  echo ""
  echo "  Uninstall:"
  echo "  --uninstall-agent <names>    Uninstall agents (comma-separated)"
  echo "  --uninstall-skill <names>    Uninstall skills (comma-separated)"
  echo "  --uninstall-rule <names>     Uninstall rules (comma-separated)"
  echo "  --uninstall-workflow <names> Uninstall workflows (comma-separated)"
  echo "  --uninstall-hook <names>     Uninstall hooks (comma-separated)"
  echo "  --uninstall-mcp <names>      Uninstall MCP servers (comma-separated)"
  echo "  -h, --help                   Show this help"
  echo ""
  echo "Examples:"
  echo "  $(basename "$0") --install                           # install defaults"
  echo "  $(basename "$0") --install-skill code-review,debugging"
  echo "  $(basename "$0") --install-group core-development"
  echo "  $(basename "$0") --template web-development          # apply template to project"
  echo "  $(basename "$0") --install-all-skills"
  echo ""
  echo "Without arguments, launches the interactive menu."
}

# Parse CLI args
if [[ $# -eq 0 ]]; then
  main_menu
  exit 0
fi

case "$1" in
  -h|--help) usage; exit 0 ;;
  --list)
    get_all_skills
    ;;
  --list-groups)
    for f in "$GROUPS_DIR"/*.group; do
      [[ -f "$f" ]] || continue
      grep -q '^\[skills\]' "$f" || continue
      _name=$(basename "$f" .group)
      _desc=$(group_description "$f")
      _count=$(parse_group "$f" | wc -l | tr -d ' ')
      printf "%-25s (%s skills)  %s\n" "$_name" "$_count" "$_desc"
    done
    ;;
  --installed)
    _found=0
    for _type in agents skills rules workflows hooks mcp; do
      load_installed_type "$_type"
      if [[ ${#INSTALLED_ITEMS[@]} -gt 0 ]]; then
        echo "${_type}:"
        for s in "${INSTALLED_ITEMS[@]}"; do echo "  $s"; done
        _found=1
      fi
    done
    [[ $_found -eq 0 ]] && echo "Nothing installed"
    ;;
  --install)
    # Install the default group
    _grp_file="$GROUPS_DIR/default.group"
    [[ -f "$_grp_file" ]] || { err "Default group not found"; exit 1; }
    info "Installing default group..."
    for _type in agents skills rules workflows hooks mcp; do
      _items=()
      while IFS= read -r s; do
        [[ -n "$s" ]] && _items+=("$s")
      done < <(parse_group_section "$_grp_file" "$_type")
      if [[ ${#_items[@]} -gt 0 ]]; then
        install_type "$_type" "${_items[@]}"
      fi
    done
    ;;
  --install-agent|--install-skill|--install-rule|--install-workflow|--install-hook|--install-mcp)
    _type="${1#--install-}"
    # Normalize singular to plural directory name
    case "$_type" in
      agent) _type="agents" ;;
      skill) _type="skills" ;;
      rule)  _type="rules" ;;
      workflow) _type="workflows" ;;
      hook)  _type="hooks" ;;
      # mcp stays as mcp
    esac
    shift
    [[ $# -eq 0 ]] && { err "Provide names (comma-separated)"; exit 1; }
    IFS=',' read -ra _items <<< "$1"
    install_type "$_type" "${_items[@]}"
    ;;
  --install-group)
    shift
    [[ $# -eq 0 ]] && { err "Provide group name"; exit 1; }
    _grp_file="$GROUPS_DIR/$1.group"
    [[ -f "$_grp_file" ]] || { err "Group not found: $1"; exit 1; }
    # Install all types from the group
    for _type in agents skills rules workflows hooks mcp; do
      _items=()
      while IFS= read -r s; do
        [[ -n "$s" ]] && _items+=("$s")
      done < <(parse_group_section "$_grp_file" "$_type")
      if [[ ${#_items[@]} -gt 0 ]]; then
        install_type "$_type" "${_items[@]}"
      fi
    done
    ;;
  --install-group-*)
    _type="${1#--install-group-}"
    shift
    [[ $# -eq 0 ]] && { err "Provide group name"; exit 1; }
    # Validate type
    case "$_type" in
      agents|skills|rules|workflows|hooks|mcp) ;;
      *) err "Unknown type: $_type (valid: agents, skills, rules, workflows, hooks, mcp)"; exit 1 ;;
    esac
    _grp_file="$GROUPS_DIR/$1.group"
    [[ -f "$_grp_file" ]] || { err "Group not found: $1"; exit 1; }
    _items=()
    while IFS= read -r s; do
      [[ -n "$s" ]] && _items+=("$s")
    done < <(parse_group_section "$_grp_file" "$_type")
    if [[ ${#_items[@]} -eq 0 ]]; then
      warn "No $_type found in group: $1"
      exit 0
    fi
    install_type "$_type" "${_items[@]}"
    ;;
  --install-all)
    # Install everything across all types
    for _type in agents skills rules workflows hooks mcp; do
      _all=()
      while IFS= read -r s; do
        [[ -n "$s" ]] && _all+=("$s")
      done < <(get_all_type "$_type")
      if [[ ${#_all[@]} -gt 0 ]]; then
        install_type "$_type" "${_all[@]}"
      fi
    done
    ;;
  --install-all-*)
    _type="${1#--install-all-}"
    case "$_type" in
      agents|skills|rules|workflows|hooks|mcp) ;;
      *) err "Unknown type: $_type (valid: agents, skills, rules, workflows, hooks, mcp)"; exit 1 ;;
    esac
    _all=()
    while IFS= read -r s; do
      [[ -n "$s" ]] && _all+=("$s")
    done < <(get_all_type "$_type")
    if [[ ${#_all[@]} -eq 0 ]]; then
      warn "No $_type found"
      exit 0
    fi
    install_type "$_type" "${_all[@]}"
    ;;
  --uninstall-agent|--uninstall-skill|--uninstall-rule|--uninstall-workflow|--uninstall-hook|--uninstall-mcp)
    _type="${1#--uninstall-}"
    case "$_type" in
      agent) _type="agents" ;;
      skill) _type="skills" ;;
      rule)  _type="rules" ;;
      workflow) _type="workflows" ;;
      hook)  _type="hooks" ;;
    esac
    shift
    [[ $# -eq 0 ]] && { err "Provide names (comma-separated)"; exit 1; }
    load_installed_type "$_type"
    IFS=',' read -ra to_remove <<< "$1"
    for r in "${to_remove[@]}"; do
      r="$(echo "$r" | tr -d ' ')"
      INSTALLED_ITEMS=($(toggle_selection "$r" "${INSTALLED_ITEMS[@]+"${INSTALLED_ITEMS[@]}"}"))
      ok "Uninstalled ${_type%s}: $r"
    done
    save_installed_type "$_type"
    ;;
  --list-templates)
    TEMPLATES_DIR="$SCRIPT_DIR/templates"
    for f in "$TEMPLATES_DIR"/*.template; do
      [[ -f "$f" ]] || continue
      _name=$(basename "$f" .template)
      _desc=$(head -1 "$f" | sed 's/^# //')
      printf "%-25s %s\n" "$_name" "$_desc"
    done
    ;;
  --template)
    shift
    [[ $# -eq 0 ]] && { err "Provide template name"; exit 1; }
    _tpl_name="$1"
    _tpl_file="$SCRIPT_DIR/templates/${_tpl_name}.template"
    [[ -f "$_tpl_file" ]] || { err "Template not found: $_tpl_name"; exit 1; }
    info "Installing template: $_tpl_name"
    _TPL_SECTION=""
    while IFS= read -r line; do
      line="${line%%#*}"
      line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
      [[ -z "$line" ]] && continue
      if [[ "$line" == "["*"]" ]]; then
        _TPL_SECTION="${line:1:${#line}-2}"
        continue
      fi
      if [[ -n "$_TPL_SECTION" ]]; then
        case "$_TPL_SECTION" in
          groups)
            _grp_file="$GROUPS_DIR/${line}.group"
            [[ -f "$_grp_file" ]] || { warn "Group not found in template: $line"; continue; }
            for _type in agents skills rules workflows hooks mcp; do
              _items=()
              while IFS= read -r s; do
                [[ -n "$s" ]] && _items+=("$s")
              done < <(parse_group_section "$_grp_file" "$_type")
              if [[ ${#_items[@]} -gt 0 ]]; then
                install_type "$_type" "${_items[@]}"
              fi
            done
            ;;
          agents|skills|rules|workflows|hooks|mcp)
            install_type "$_TPL_SECTION" "$line"
            ;;
        esac
      fi
    done < "$_tpl_file"
    # Save template as project config if not --global
    _global=false
    for _a in "$@"; do [[ "$_a" == "--global" || "$_a" == "-g" ]] && _global=true; done
    if [[ "$_global" == false ]]; then
      _project_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
      echo "$_tpl_name" > "$_project_root/.ai-management"
      ok "Saved template → $_project_root/.ai-management"
    fi
    info "Run ${CYAN}sync.sh --template $_tpl_name${NC} to deploy"
    ;;
  *)
    err "Unknown option: $1"
    usage
    exit 1
    ;;
esac
