from __future__ import annotations

from pathlib import Path
from typing import List, Sequence

from .groups import CONTENT_TYPES, get_all_type, group_path, parse_group_section, parse_section_file, template_path
from .utils import AI_MGMT_HOME, INSTALLED_DIR, SYNC_TEMPLATE_FILE, CLIError, dedupe, ensure_dir, info, ok, singular_label, warn

INSTALLED_SKILLS: List[str] = []


def migrate_legacy_installed() -> None:
    legacy = AI_MGMT_HOME / "installed-skills.conf"
    target = INSTALLED_DIR / "skills.conf"
    if legacy.exists() and not target.exists():
        ensure_dir(INSTALLED_DIR)
        target.write_text(legacy.read_text(encoding="utf-8"), encoding="utf-8")
        legacy.unlink()


def installed_conf_path(content_type: str) -> Path:
    return INSTALLED_DIR / f"{content_type}.conf"


def load_installed_type(content_type: str) -> List[str]:
    path = installed_conf_path(content_type)
    items: List[str] = []
    if path.exists():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].replace(" ", "").strip()
            if line:
                items.append(line)
    return items


def load_installed() -> List[str]:
    global INSTALLED_SKILLS
    INSTALLED_SKILLS = load_installed_type("skills")
    return INSTALLED_SKILLS


def save_installed_type(content_type: str, items: Sequence[str]) -> None:
    ensure_dir(INSTALLED_DIR)
    path = installed_conf_path(content_type)
    ordered = dedupe(item for item in items if item)
    lines = [f"# AI Management installed {content_type}", "# Auto-generated by wdm ai"]
    lines.extend(ordered)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    if content_type == "skills":
        global INSTALLED_SKILLS
        INSTALLED_SKILLS = list(ordered)


def save_installed(items: Sequence[str]) -> None:
    save_installed_type("skills", items)


def install_type(content_type: str, names: Sequence[str]) -> None:
    names = [name.strip() for name in names if name.strip()]
    print()
    print(f"\033[1m── Installing {len(names)} {content_type} ──\033[0m")
    installed = load_installed_type(content_type)
    count = 0
    for name in names:
        from .groups import resolve_item_path

        path = resolve_item_path(content_type, name)
        if path.exists():
            if name not in installed:
                installed.append(name)
            ok(name)
            count += 1
        else:
            warn(f"{singular_label(content_type)} not found: {name}")
    save_installed_type(content_type, installed)
    print()
    ok(f"Installed {count} {content_type} → {installed_conf_path(content_type)}")
    print()
    info("Run wdm ai sync to deploy to your harnesses")


def uninstall_type(content_type: str, names: Sequence[str]) -> None:
    installed = load_installed_type(content_type)
    updated = list(installed)
    for raw_name in names:
        name = raw_name.strip()
        if not name:
            continue
        updated = [value for value in updated if value != name]
        ok(f"Uninstalled {singular_label(content_type)}: {name}")
    save_installed_type(content_type, updated)


def show_installed() -> None:
    found = False
    for content_type in CONTENT_TYPES:
        items = load_installed_type(content_type)
        if items:
            print(f"{content_type}:")
            for item in items:
                print(f"  {item}")
            found = True
    if not found:
        print("Nothing installed")


def install_group(group_name: str, only_type: str = "") -> None:
    file_path = group_path(group_name)
    if not file_path.exists():
        raise CLIError(f"Group not found: {group_name}")
    for content_type in CONTENT_TYPES:
        if only_type and content_type != only_type:
            continue
        items = parse_group_section(file_path, content_type)
        if items:
            install_type(content_type, items)
        elif only_type:
            warn(f"No {only_type} found in group: {group_name}")


def install_all(only_type: str = "") -> None:
    for content_type in CONTENT_TYPES:
        if only_type and content_type != only_type:
            continue
        items = get_all_type(content_type)
        if items:
            install_type(content_type, items)
        elif only_type:
            warn(f"No {only_type} found")


def install_template(template_name: str, global_mode: bool) -> None:
    raise CLIError("Repo templates have been removed. Use groups for repo sets.")


migrate_legacy_installed()
